# Construcción y Curaduría del Corpus de Clasificación de Funciones de Cita

## 1. Introducción y Justificación del Problema

En la literatura científica, las citas bibliográficas cumplen propósitos retóricos diversos: desde contextualizar antecedentes (*Background*) o señalar limitaciones metodológicas (*Gap*), hasta fundamentar desarrollos teóricos (*Basis*) o contrastar resultados experimentales (*Comparison*)[cite: 5]. Sin embargo, la gran mayoría de los corpus estándar disponibles en Procesamiento del Lenguaje Natural (PLN) sufren de un severo desbalance de clases: las funciones genéricas concentran la mayor parte de las instancias, mientras que las categorías críticas para el análisis del progreso científico quedan relegadas a una representación marginal.

El objetivo central de este cuaderno no es simplemente recopilar texto académico, sino **diseñar un pipeline de ingeniería de datos riguroso, reproducible y balanceado**. Para que un modelo predictivo o un evaluador humano pueda discriminar eficazmente entre propósitos de citación, se requiere un conjunto de datos equilibrado a gran escala (18.000 instancias distribuidas equitativamente en 9 categorías retóricas)[cite: 5].

A lo largo de este pipeline se toman decisiones arquitectónicas orientadas a resolver desafíos específicos de curaduría de datos en PLN:
* **Ingesta Multi-Fuente Dirigida:** Superar la escasez de ejemplos minoritarios en corpus tradicionales integrando consultas programáticas masivas y asíncronas sobre Semantic Scholar.
* **Rescate Semántico Asistido por LLMs:** Emplear modelos de lenguaje de última generación mediante salidas estructuradas para desambiguar citas complejas sin introducir sesgos de alucinación.
* **Aislamiento por Documento (*No-Leakage Guarantee*):** Garantizar la validez metodológica en la evaluación separando conjuntos por pares documentales (`citing_paper` – `cited_paper`), evitando fugas de información (*data leakage*).
* **Enriquecimiento Denso (*Dense Retrieval*):** Alinear cada contexto de citación con los fragmentos más relevantes del documento citado utilizando representaciones densas con SciBERT, respetando las fronteras naturales del discurso científico[cite: 5].

## 2. Configuración del Entorno y Dependencias

En esta celda se instalan y cargan todos los módulos y paquetes requeridos para ejecutar el flujo de trabajo completo: utilidades del sistema, clientes de red asíncronos, herramientas de procesamiento y particionado de datos, modelos de lenguaje y representaciones densas, integración con APIs externas y gestión de almacenamiento.

In [2]:
# 0. Instalación de paquetes
!pip install -q datasets transformers google-genai aiohttp pydantic

# Manejo de archivos, rutas del sistema y descargas básicas
import io
import json
import os
import re
import tarfile
import time
import urllib.parse
import urllib.request

# Conexiones web y llamadas asíncronas
import aiohttp
import asyncio
import requests

# Tablas y particiones de datos
import numpy as np
import pandas as pd
from sklearn.model_selection import GroupShuffleSplit, train_test_split

# Modelos, tokenizadores y cálculo tensorial
import torch
import torch.nn.functional as F
from datasets import load_dataset
from transformers import AutoModel, AutoTokenizer

# Conexión con Gemini y esquemas de validación
from google import genai
from google.genai import types
from pydantic import BaseModel, Field

# Conexión con Drive y barras de progreso visuales
from google.colab import drive, userdata
from tqdm.auto import tqdm

## 3. Conexión de Almacenamiento Persistente y Directorio de Trabajo

En esta celda se vincula el entorno de ejecución con Google Drive y se establece la ruta base del proyecto. Esta decisión asegura la persistencia de datos a lo largo de todas las etapas, permitiendo almacenar puntos de control (*checkpoints*), datasets intermedios y particiones definitivas sin riesgo de pérdida por desconexiones o reinicios de la máquina virtual.

In [3]:
# Conectamos Google Drive para guardar los datasets y checkpoints
drive.mount("/content/drive")

# Creamos la carpeta del proyecto si no existe
DRIVE_DIR = "/content/drive/MyDrive/proyecto_nlp_citas"
os.makedirs(DRIVE_DIR, exist_ok=True)

print(f"Directorio de trabajo configurado: {DRIVE_DIR}")

Mounted at /content/drive
Directorio de trabajo configurado: /content/drive/MyDrive/proyecto_nlp_citas

## 4. Ingesta y Estandarización de Fuentes Primarias (SciCite y SciTail)

En esta celda se descargan e integran dos corpus científicos complementarios para conformar la base inicial de citas:
* **SciCite:** Aporta contextos reales de citación junto con metadatos explícitos de sección retórica e identificadores de pares documentales.
* **SciTail:** Proporciona oraciones formales de literatura científica que enriquecen la variedad estilística y gramatical del texto.

Las decisiones clave en esta fase incluyen:
* **Estandarización del esquema:** Unificar ambas fuentes bajo una estructura común (`citation_context`, `rhetorical_section`, `citing_paper_id`, `cited_paper_id` y `source_dataset`).
* **Filtro de longitud mínima:** Excluir textos con menos de 6 palabras para descartar fragmentos truncados o citas sin carga semántica suficiente.
* **Desduplicación:** Eliminar contextos repetidos para prevenir sesgos de memorización y garantizar que cada registro sea único antes del etiquetado.

In [ ]:
archivo_salida_unificado = os.path.join(
    DRIVE_DIR, "dataset_citas_unificado.csv"
)

# 1. Descargamos y procesamos SciCite
print("1/3. Descargando SciCite...")
scicite_url = (
    "https://s3-us-west-2.amazonaws.com/ai2-s2-research/scicite/scicite.tar.gz"
)
req = urllib.request.Request(
    scicite_url, headers={"User-Agent": "Mozilla/5.0"}
)
with urllib.request.urlopen(req) as resp:
  tar_bytes = io.BytesIO(resp.read())

with tarfile.open(fileobj=tar_bytes, mode="r:gz") as tar:
  scicite_records = [
      pd.read_json(io.BytesIO(tar.extractfile(m).read()), lines=True)
      for m in tar.getmembers()
      if m.name.endswith(".jsonl") and tar.extractfile(m) is not None
  ]

df_scicite_all = pd.concat(scicite_records, ignore_index=True)
df_scicite = pd.DataFrame({
    "citation_context": df_scicite_all["string"],
    "rhetorical_section": df_scicite_all["sectionName"].fillna("Unknown"),
    "citing_paper_id": df_scicite_all["citingPaperId"],
    "cited_paper_id": df_scicite_all["citedPaperId"],
    "source_dataset": "scicite",
})

# 2. Descargamos y procesamos SciTail
print("2/3. Descargando SciTail...")
dataset_scitail = load_dataset("allenai/scitail", "snli_format")
df_scitail_all = pd.concat(
    [
        dataset_scitail["train"].to_pandas(),
        dataset_scitail["validation"].to_pandas(),
        dataset_scitail["test"].to_pandas(),
    ],
    ignore_index=True,
)

df_scitail = pd.DataFrame({
    "citation_context": df_scitail_all["sentence1"],
    "rhetorical_section": "Scientific Body",
    "citing_paper_id": [
        f"scitail_citing_{i}" for i in range(len(df_scitail_all))
    ],
    "cited_paper_id": [f"scitail_cited_{i}" for i in range(len(df_scitail_all))],
    "source_dataset": "scitail",
})

# 3. Limpiamos, desduplicamos y guardamos el corpus inicial
print("3/3. Guardando corpus unificado en Drive...")
df_unificado = pd.concat([df_scicite, df_scitail], ignore_index=True)
df_unificado = df_unificado[
    df_unificado["citation_context"].str.split().str.len() >= 6
]
df_unificado = df_unificado.drop_duplicates(
    subset=["citation_context"]
).reset_index(drop=True)

df_unificado.to_csv(archivo_salida_unificado, index=False)
print(f"Dataset base listo: {len(df_unificado)} registros únicos guardados.")

1/3. Descargando y procesando SciCite oficial...

/tmp/ipykernel_1871/3718749486.py:25: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall(path=scicite_dir)

-> SciCite procesado: 11020 registros

2/3. Descargando y procesando SciTail...

/usr/local/lib/python3.13/dist-packages/huggingface_hub/utils/_auth.py:138: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
  warnings.warn(f"\nError while fetching `HF_TOKEN` secret value from your vault: '{str(e)}'.")
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/10.1k [00:00<?, ?B/s]

snli_format/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 6.42MB

snli_format/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

snli_format/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B /  653kB

snli_format/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

snli_format/validation-00000-of-00001.pa(…): reconstructing file:   0%|          |  0.00B /  400kB

snli_format/validation-00000-of-00001.pa(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/23596 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2126 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1304 [00:00<?, ? examples/s]

-> SciTail procesado: 27026 registros

3/3. Consolidando y guardando archivo unificado en Google Drive...

============================================================
¡DATASET UNIFICADO GUARDADO EXITOSAMENTE EN GOOGLE DRIVE!
Total registros consolidados: 25000
Ruta: /content/drive/MyDrive/proyecto_nlp_citas/dataset_citas_unificado.csv
============================================================

,citation_context,rhetorical_section,citing_paper_id,cited_paper_id,cited_paper_title,cited_paper_abstract,source_dataset
0,Most primitive type of conducting cells and th...,Scientific Body,scitail_citing_4125,scitail_cited_4125,,Conifers are the most prevalent type of gymnos...,scitail
1,THE GLOBAL POSITIONING SYSTEM The Global Posit...,Scientific Body,scitail_citing_12973,scitail_cited_12973,,We call the worldwide radio-navigation system ...,scitail
2,(Pottiaceae) exhibits a high level of genetic ...,Introduction,291ca965a80c0b484e70533599b2898f3c9b7cf7,63daf1741972395162371e6e9bf12348828cfe44,,,scicite

## 5. Clasificación Semántica Dirigida y Rescate de Clases Deficitarias con LLM

En esta celda se implementa el proceso de clasificación inicial asistido por un modelo de lenguaje masivo (LLM) y la estrategia de rescate de categorías minoritarias.

Las decisiones metodológicas tomadas en este bloque responden a:
* **Pre-filtrado léxico de candidatos:** En lugar de clasificar indiscriminadamente todo el corpus —lo que consumiría recursos excesivos en citas genéricas—, se aplican expresiones regulares específicas sobre marcadores discursivos académicos (*e.g.*, extensiones, comparaciones o limitaciones) para aislar únicamente las citas potencialmente pertenecientes a clases deficitarias.
* **Esquema de salida estructurado (`CitationClassification`):** Se exige al modelo un objeto tipado vía Pydantic donde cada una de las 9 clases recibe un puntaje probabilístico continuo ($0.0$ a $1.0$), además de la categoría predominante. Esto evita salidas conversacionales no deterministas y permite disponer de la distribución completa de confianza.
* **Procesamiento asíncrono con control de concurrencia y persistencia por lotes:** Se utiliza `asyncio.Semaphore` para maximizar el rendimiento sin saturar la cuota de la API, guardando puntos de control periódicos en disco para asegurar tolerancia a fallos y reanudación automática.
* **Mecanismo de rescate probabilístico secundario:** Cuando la predicción dura (*hard label*) clasifica un contexto como genérico (*Background* o *Application*), se inspecciona el vector continuo de probabilidades. Si una categoría deficitaria presenta una confianza significativa ($\ge 0.35$ o $\ge 0.25$ como hipótesis dominante entre las minoritarias), se rescata dicha etiqueta para equilibrar la distribución del corpus antes de consolidar el archivo maestro.

In [ ]:
# 1. Configuración de API y rutas persistentes
archivo_base = os.path.join(DRIVE_DIR, "dataset_citas_unificado.csv")
checkpoint_etiquetado = os.path.join(
    DRIVE_DIR, "checkpoint_candidatos_etiquetados.csv"
)
archivo_master = os.path.join(
    DRIVE_DIR, "dataset_citas_reales_definitivo_master.csv"
)

client = genai.Client(api_key=userdata.get("API_GEMINI"))
MODELO = "gemini-3.5-flash-lite"

CATEGORIAS = [
    "Background",
    "Gap",
    "Basis",
    "Comparison",
    "Application",
    "Modification_Improvement",
    "Evidence",
    "Identification_of_the_Originator",
    "Further_Reading",
]

CLASES_DEFICITARIAS = [
    "Modification_Improvement",
    "Further_Reading",
    "Identification_of_the_Originator",
    "Basis",
    "Gap",
    "Comparison",
    "Evidence",
]

# 2. Pre-filtro léxico sobre las citas base
PATRONES = {
    "Modification_Improvement": (
        r"\b(extend|extended|extending|modified|modification|adapting|adapted"
        r" from|improved upon|improvement on|an extension|we build"
        r" upon|variant of)\b"
    ),
    "Further_Reading": (
        r"\b(see (also )?\[|refer to|for further|for details|for a survey|for"
        r" a review|for more information|comprehensively reviewed in|tutorial)\b"
    ),
    "Gap": (
        r"\b(however|although|remains unclear|little is known|fails"
        r" to|lacks|open question|limitation|unaddressed|scarcely"
        r" studied|shortcoming)\b"
    ),
    "Basis": (
        r"\b(based on the (theory|framework|model|formulation)|follows the"
        r" approach of|grounded in|starting point|foundational work"
        r" of|premise)\b"
    ),
    "Identification_of_the_Originator": (
        r"\b(first (proposed|introduced|developed|described)|pioneered"
        r" by|originally formulated by|credited to|seminal work by)\b"
    ),
    "Comparison": (
        r"\b(compared to|in contrast with|outperforms|better than|differs"
        r" from|consistent with|contrary to)\b"
    ),
}

df_corpus = pd.read_csv(archivo_base)
filtro_regex = "|".join([f"({p})" for p in PATRONES.values()])

df_candidatos = df_corpus[
    df_corpus["citation_context"].str.contains(
        filtro_regex, flags=re.IGNORECASE, regex=True, na=False
    )
].reset_index(drop=True)

print(f"Citas cargadas: {len(df_corpus)} | Candidatos a clasificar: {len(df_candidatos)}")


# 3. Esquema estructurado y llamada a Gemini con Criterios de la Guía
class CitationClassification(BaseModel):
    Background: float = Field(description="0.0 a 1.0 según criterios de contexto general y revisión")
    Gap: float = Field(description="0.0 a 1.0 según identificación de limitaciones y vacíos")
    Basis: float = Field(description="0.0 a 1.0 según punto de partida teórico/conceptual o base fundacional")
    Comparison: float = Field(description="0.0 a 1.0 según contraste de resultados, datos o métodos")
    Application: float = Field(description="0.0 a 1.0 según uso directo sin modificación de herramientas/métodos")
    Modification_Improvement: float = Field(description="0.0 a 1.0 según adaptación o mejora metodológica")
    Evidence: float = Field(description="0.0 a 1.0 según soporte empírico, justificación de diseño o hallazgos")
    Identification_of_the_Originator: float = Field(description="0.0 a 1.0 según atribución de autoría original o pionera")
    Further_Reading: float = Field(description="0.0 a 1.0 según redirección a literatura complementaria")
    predicted_label: str = Field(description="Categoría única predominante")


async def clasificar_registro(semaphore, idx, texto, seccion, max_retries=4):
    async with semaphore:
        prompt = f"""You are an expert NLP annotator specializing in citation function classification.
Classify the following citation context strictly following these definition criteria:

1. Background: Provides context, historical development, general literature review, or broad overview of the field.
2. Gap: Highlights unexplored areas, limitations, shortcomings, unanswered questions, or what remains unknown.
3. Basis: Serves as the intellectual starting point, foundational premise, hypothesis, or theoretical foundation upon which the current work builds.
4. Comparison: Compares methodologies, findings, models, or performance between the current and cited work (similarities, differences, advantages).
5. Application: Directly applies or uses a method, tool, algorithm, formula, or dataset WITHOUT modification.
6. Modification_Improvement: Adapts, modifies, expands, or enhances existing methods, models, or tools to fit new conditions.
7. Evidence: Cites prior work to substantiate claims, support hypotheses, justify methodological designs, or validate empirical findings.
8. Identification_of_the_Originator: Formally credits the pioneer or original publication that first introduced a concept, algorithm, or theory.
9. Further_Reading: Explicitly directs readers to external/supplementary sources, tutorials, surveys, or extended documentation for deeper details.

Input Data:
- Rhetorical Section: {seccion}
- Citation Context: "{texto}"

Output requirements:
Assign a confidence score from 0.0 to 1.0 for each of the 9 categories and set 'predicted_label' to the single dominant category."""

        for attempt in range(max_retries):
            try:
                res = await client.aio.models.generate_content(
                    model=MODELO,
                    contents=prompt,
                    config=types.GenerateContentConfig(
                        response_mime_type="application/json",
                        response_schema=CitationClassification,
                        temperature=0.0,
                    ),
                )
                data = json.loads(res.text)
                label = data.get("predicted_label", "Background")
                if label not in CATEGORIAS:
                    label = max(
                        CATEGORIAS,
                        key=lambda c: (
                            data.get(c, 0.0)
                            if isinstance(data.get(c), (int, float))
                            else 0.0
                        ),
                    )
                return idx, label, data
            except Exception as e:
                wait = (2**attempt) + 1
                if any(
                    err in str(e)
                    for err in ["503", "429", "RESOURCE_EXHAUSTED", "UNAVAILABLE"]
                ):
                    await asyncio.sleep(wait)
                else:
                    if attempt == max_retries - 1:
                        return idx, "Error", {}
                    await asyncio.sleep(wait)
        return idx, "Error", {}


# 4. Pipeline asíncrono con guardado por lotes
async def ejecutar_pipeline(
    df_input, checkpoint_path, batch_size=200, max_concurrency=6
):
    if df_input.empty:
        return pd.DataFrame()
    semaphore = asyncio.Semaphore(max_concurrency)

    if os.path.exists(checkpoint_path):
        df_proc = pd.read_csv(checkpoint_path)
        procesados = set(df_proc["citation_context"].astype(str))
        df_pend = df_input[
            ~df_input["citation_context"].astype(str).isin(procesados)
        ].copy()
        print(f"Reanudando: {len(df_proc)} ya procesados | {len(df_pend)} pendientes.")
    else:
        df_proc = pd.DataFrame()
        df_pend = df_input.copy()

    total = len(df_pend)
    for i in range(0, total, batch_size):
        batch = df_pend.iloc[i : i + batch_size]
        tasks = [
            clasificar_registro(
                semaphore,
                idx,
                row["citation_context"],
                row.get("rhetorical_section", "Body"),
            )
            for idx, row in batch.iterrows()
        ]
        print(f"Clasificando lote {i // batch_size + 1}/{(total + batch_size - 1) // batch_size}...")
        respuestas = await asyncio.gather(*tasks)

        nuevos = []
        for idx, label, scores in respuestas:
            if label != "Error":
                fila = batch.loc[idx].to_dict()
                fila["predicted_label"] = label
                fila["scores_json"] = json.dumps(scores)
                nuevos.append(fila)

        if nuevos:
            df_proc = pd.concat([df_proc, pd.DataFrame(nuevos)], ignore_index=True)
            df_proc.to_csv(checkpoint_path, index=False)

    return df_proc


df_etiquetados = await ejecutar_pipeline(df_candidatos, checkpoint_etiquetado)


# 5. Rescate secundario y guardado en Master
def rescate_profundo(row):
    label = row["predicted_label"]
    if label in CLASES_DEFICITARIAS:
        return label
    try:
        scores = json.loads(row["scores_json"])
        for cat in CLASES_DEFICITARIAS:
            if float(scores.get(cat, 0.0)) >= 0.35:
                return cat
        mejor = max(CLASES_DEFICITARIAS, key=lambda c: float(scores.get(c, 0.0)))
        if float(scores.get(mejor, 0.0)) >= 0.25:
            return mejor
    except:
        pass
    return label


df_etiquetados["etiqueta_rescatada"] = df_etiquetados.apply(
    rescate_profundo, axis=1
)
df_etiquetados.to_csv(archivo_master, index=False)

print("\n" + "=" * 60)
print("DISTRIBUCIÓN INICIAL CONSOLIDADA EN MASTER:")
print("=" * 60)
conteo = df_etiquetados["etiqueta_rescatada"].value_counts()
resumen = pd.DataFrame({
    "Instancias Reales": conteo,
    "Faltante para 2.000": [max(0, 2000 - c) for c in conteo],
})
display(resumen)
print(f"\nDéficit restante: {sum(resumen['Faltante para 2.000'])}")

Iniciando procesamiento desde cero: 25000 registros.
Procesando lote 1/100...
-> Checkpoint en Drive actualizado: 250 registros guardados.
Procesando lote 2/100...
-> Checkpoint en Drive actualizado: 500 registros guardados.
Procesando lote 3/100...
-> Checkpoint en Drive actualizado: 750 registros guardados.
Procesando lote 4/100...
-> Checkpoint en Drive actualizado: 1000 registros guardados.
Procesando lote 5/100...
-> Checkpoint en Drive actualizado: 1250 registros guardados.
Procesando lote 6/100...
-> Checkpoint en Drive actualizado: 1500 registros guardados.
Procesando lote 7/100...
-> Checkpoint en Drive actualizado: 1750 registros guardados.
Procesando lote 8/100...
-> Checkpoint en Drive actualizado: 2000 registros guardados.
Procesando lote 9/100...
-> Checkpoint en Drive actualizado: 2250 registros guardados.
Procesando lote 10/100...
-> Checkpoint en Drive actualizado: 2500 registros guardados.
Procesando lote 11/100...
-> Checkpoint en Drive actualizado: 2750 registros guardados.
Procesando lote 12/100...
-> Checkpoint en Drive actualizado: 3000 registros guardados.
Procesando lote 13/100...
-> Checkpoint en Drive actualizado: 3250 registros guardados.
Procesando lote 14/100...
-> Checkpoint en Drive actualizado: 3500 registros guardados.
Procesando lote 15/100...
-> Checkpoint en Drive actualizado: 3750 registros guardados.
Procesando lote 16/100...
-> Checkpoint en Drive actualizado: 4000 registros guardados.
Procesando lote 17/100...
-> Checkpoint en Drive actualizado: 4250 registros guardados.
Procesando lote 18/100...
-> Checkpoint en Drive actualizado: 4500 registros guardados.
Procesando lote 19/100...
-> Checkpoint en Drive actualizado: 4750 registros guardados.
Procesando lote 20/100...
-> Checkpoint en Drive actualizado: 5000 registros guardados.
Procesando lote 21/100...
-> Checkpoint en Drive actualizado: 5250 registros guardados.
Procesando lote 22/100...
-> Checkpoint en Drive actualizado: 5500 registros guardados.
Procesando lote 23/100...
-> Checkpoint en Drive actualizado: 5750 registros guardados.
Procesando lote 24/100...
-> Checkpoint en Drive actualizado: 6000 registros guardados.
Procesando lote 25/100...
-> Checkpoint en Drive actualizado: 6250 registros guardados.
Procesando lote 26/100...
-> Checkpoint en Drive actualizado: 6500 registros guardados.
Procesando lote 27/100...
-> Checkpoint en Drive actualizado: 6750 registros guardados.
Procesando lote 28/100...
-> Checkpoint en Drive actualizado: 7000 registros guardados.
Procesando lote 29/100...
-> Checkpoint en Drive actualizado: 7250 registros guardados.
Procesando lote 30/100...
-> Checkpoint en Drive actualizado: 7500 registros guardados.
Procesando lote 31/100...
-> Checkpoint en Drive actualizado: 7750 registros guardados.
Procesando lote 32/100...
-> Checkpoint en Drive actualizado: 8000 registros guardados.
Procesando lote 33/100...
-> Checkpoint en Drive actualizado: 8250 registros guardados.
Procesando lote 34/100...
-> Checkpoint en Drive actualizado: 8500 registros guardados.
Procesando lote 35/100...
-> Checkpoint en Drive actualizado: 8750 registros guardados.
Procesando lote 36/100...
-> Checkpoint en Drive actualizado: 9000 registros guardados.
Procesando lote 37/100...
-> Checkpoint en Drive actualizado: 9250 registros guardados.
Procesando lote 38/100...
-> Checkpoint en Drive actualizado: 9500 registros guardados.
Procesando lote 39/100...
-> Checkpoint en Drive actualizado: 9750 registros guardados.
Procesando lote 40/100...
-> Checkpoint en Drive actualizado: 10000 registros guardados.
Procesando lote 41/100...
-> Checkpoint en Drive actualizado: 10250 registros guardados.
Procesando lote 42/100...
-> Checkpoint en Drive actualizado: 10500 registros guardados.
Procesando lote 43/100...
-> Checkpoint en Drive actualizado: 10750 registros guardados.
Procesando lote 44/100...
-> Checkpoint en Drive actualizado: 11000 registros guardados.
Procesando lote 45/100...
-> Checkpoint en Drive actualizado: 11250 registros guardados.
Procesando lote 46/100...
-> Checkpoint en Drive actualizado: 11500 registros guardados.
Procesando lote 47/100...
-> Checkpoint en Drive actualizado: 11750 registros guardados.
Procesando lote 48/100...
-> Checkpoint en Drive actualizado: 12000 registros guardados.
Procesando lote 49/100...
-> Checkpoint en Drive actualizado: 12250 registros guardados.
Procesando lote 50/100...
-> Checkpoint en Drive actualizado: 12500 registros guardados.
Procesando lote 51/100...
-> Checkpoint en Drive actualizado: 12750 registros guardados.
Procesando lote 52/100...
-> Checkpoint en Drive actualizado: 13000 registros guardados.
Procesando lote 53/100...
-> Checkpoint en Drive actualizado: 13250 registros guardados.
Procesando lote 54/100...
-> Checkpoint en Drive actualizado: 13500 registros guardados.
Procesando lote 55/100...
-> Checkpoint en Drive actualizado: 13750 registros guardados.
Procesando lote 56/100...
-> Checkpoint en Drive actualizado: 14000 registros guardados.
Procesando lote 57/100...
-> Checkpoint en Drive actualizado: 14250 registros guardados.
Procesando lote 58/100...
-> Checkpoint en Drive actualizado: 14500 registros guardados.
Procesando lote 59/100...
-> Checkpoint en Drive actualizado: 14750 registros guardados.
Procesando lote 60/100...
-> Checkpoint en Drive actualizado: 15000 registros guardados.
Procesando lote 61/100...
-> Checkpoint en Drive actualizado: 15250 registros guardados.
Procesando lote 62/100...
-> Checkpoint en Drive actualizado: 15500 registros guardados.
Procesando lote 63/100...
-> Checkpoint en Drive actualizado: 15750 registros guardados.
Procesando lote 64/100...
-> Checkpoint en Drive actualizado: 16000 registros guardados.
Procesando lote 65/100...
-> Checkpoint en Drive actualizado: 16250 registros guardados.
Procesando lote 66/100...
-> Checkpoint en Drive actualizado: 16500 registros guardados.
Procesando lote 67/100...
-> Checkpoint en Drive actualizado: 16750 registros guardados.
Procesando lote 68/100...
-> Checkpoint en Drive actualizado: 17000 registros guardados.
Procesando lote 69/100...
-> Checkpoint en Drive actualizado: 17250 registros guardados.
Procesando lote 70/100...
-> Checkpoint en Drive actualizado: 17500 registros guardados.
Procesando lote 71/100...
-> Checkpoint en Drive actualizado: 17750 registros guardados.
Procesando lote 72/100...
-> Checkpoint en Drive actualizado: 18000 registros guardados.
Procesando lote 73/100...
-> Checkpoint en Drive actualizado: 18250 registros guardados.
Procesando lote 74/100...
-> Checkpoint en Drive actualizado: 18500 registros guardados.
Procesando lote 75/100...
-> Checkpoint en Drive actualizado: 18750 registros guardados.
Procesando lote 76/100...
-> Checkpoint en Drive actualizado: 19000 registros guardados.
Procesando lote 77/100...
-> Checkpoint en Drive actualizado: 19250 registros guardados.
Procesando lote 78/100...
-> Checkpoint en Drive actualizado: 19500 registros guardados.
Procesando lote 79/100...
-> Checkpoint en Drive actualizado: 19750 registros guardados.
Procesando lote 80/100...
-> Checkpoint en Drive actualizado: 20000 registros guardados.
Procesando lote 81/100...
-> Checkpoint en Drive actualizado: 20250 registros guardados.
Procesando lote 82/100...
-> Checkpoint en Drive actualizado: 20500 registros guardados.
Procesando lote 83/100...
-> Checkpoint en Drive actualizado: 20750 registros guardados.
Procesando lote 84/100...
-> Checkpoint en Drive actualizado: 21000 registros guardados.
Procesando lote 85/100...
-> Checkpoint en Drive actualizado: 21250 registros guardados.
Procesando lote 86/100...
-> Checkpoint en Drive actualizado: 21500 registros guardados.
Procesando lote 87/100...
-> Checkpoint en Drive actualizado: 21750 registros guardados.
Procesando lote 88/100...
-> Checkpoint en Drive actualizado: 22000 registros guardados.
Procesando lote 89/100...
-> Checkpoint en Drive actualizado: 22250 registros guardados.
Procesando lote 90/100...
-> Checkpoint en Drive actualizado: 22500 registros guardados.
Procesando lote 91/100...
-> Checkpoint en Drive actualizado: 22750 registros guardados.
Procesando lote 92/100...
-> Checkpoint en Drive actualizado: 23000 registros guardados.
Procesando lote 93/100...
-> Checkpoint en Drive actualizado: 23250 registros guardados.
Procesando lote 94/100...
-> Checkpoint en Drive actualizado: 23500 registros guardados.
Procesando lote 95/100...
-> Checkpoint en Drive actualizado: 23750 registros guardados.
Procesando lote 96/100...
-> Checkpoint en Drive actualizado: 24000 registros guardados.
Procesando lote 97/100...
-> Checkpoint en Drive actualizado: 24250 registros guardados.
Procesando lote 98/100...
-> Checkpoint en Drive actualizado: 24500 registros guardados.
Procesando lote 99/100...
-> Checkpoint en Drive actualizado: 24750 registros guardados.
Procesando lote 100/100...
-> Checkpoint en Drive actualizado: 25000 registros guardados.

## 6. Consolidación de Fuentes Previas y Justificación de Déficit Previo a S2

En esta celda se unifican y analizan todos los conjuntos de datos obtenidos en las etapas de experimentación preliminares.

Las decisiones metodológicas tomadas en este bloque responden a:
* **Homogeneización del esquema histórico:** Diversas iteraciones almacenaron las predicciones bajo nombres de columnas diferentes (`predicted_label` o `etiqueta_rescatada`); aquí se estandarizan a un formato común y se aseguran las secciones retóricas mínimas.
* **Depuración y desduplicación estricta:** Se descartan predicciones erróneas y se eliminan duplicados a nivel de contexto de citación (`citation_context`), garantizando que cada registro consolidado en el archivo maestro sea único y representativo.
* **Auditoría de calidad y longitud textual:** Se verifican nulos y se evalúan estadísticas de longitud promedio en palabras por categoría para corroborar que los contextos recopilados retienen información semántica sustantiva y no fragmentos triviales.
* **Diagnóstico formal de desbalance y justificación empírica:** El cálculo explícito del déficit frente a la meta de 2.000 instancias por clase evidencia cuantitativamente que los corpus clásicos y los filtros léxicos iniciales no logran abastecer las categorías minoritarias (*Modification_Improvement*, *Further_Reading*, *Gap*, entre otras). Esto fundamenta de manera justificada y verificable la necesidad de saltar hacia una fase de ingesta masiva y dirigida a través de la API de Semantic Scholar (S2).

In [ ]:
# Consolidación de Fuentes Previas
N_OBJETIVO = 2000

CATEGORIAS = [
    "Background", "Gap", "Basis", "Comparison",
    "Application", "Modification_Improvement", "Evidence",
    "Identification_of_the_Originator", "Further_Reading"
]

# 1. Archivos generados en las etapas preliminares
archivos_previos = [
    'dataset_citas_etiquetado.csv',
    'dataset_citas_reales_maximizadas.csv',
    'dataset_aclarc_clasificado_checkpoint.csv',
    'dataset_candidatos_remanentes_etiquetados.csv',
    'dataset_citas_extra_reales_checkpoint.csv',
    'dataset_citas_reales_consolidadas_final.csv',
    'dataset_citas_reales_maximizadas_v2.csv',
    'dataset_citas_reales_maximizadas_v3.csv'
]

dfs = []
for f in archivos_previos:
    ruta = os.path.join(DRIVE_DIR, f)
    if os.path.exists(ruta):
        df_temp = pd.read_csv(ruta)

        # Homogeneizar la columna de etiqueta
        if 'etiqueta_rescatada' not in df_temp.columns and 'predicted_label' in df_temp.columns:
            df_temp['etiqueta_rescatada'] = df_temp['predicted_label']
        if 'rhetorical_section' not in df_temp.columns:
            df_temp['rhetorical_section'] = 'Body'

        dfs.append(df_temp[['citation_context', 'rhetorical_section', 'etiqueta_rescatada']])

# 2. Consolidar y desduplicar
df_master_real = pd.concat(dfs, ignore_index=True).drop_duplicates(subset=['citation_context'])
df_master_real = df_master_real[df_master_real['etiqueta_rescatada'] != 'Error'].reset_index(drop=True)

# Guardar estado consolidado previo a S2
archivo_master = os.path.join(DRIVE_DIR, 'dataset_citas_reales_definitivo_master.csv')
df_master_real.to_csv(archivo_master, index=False)

# 3. Reporte de Auditoría y Justificación de Necesidad de S2
print("=" * 75)
print("   ESTADO CONSOLIDADO PREVIO A S2: AUDITORÍA Y JUSTIFICACIÓN DE DÉFICIT")
print("=" * 75)
print(f"Total registros únicos consolidados: {len(df_master_real)}")
print("\n--- Valores nulos por columna ---")
print(df_master_real.isnull().sum())

# Distribución y cálculo de déficit
conteo = df_master_real['etiqueta_rescatada'].value_counts()
porcentaje = (df_master_real['etiqueta_rescatada'].value_counts(normalize=True) * 100).round(2)

resumen_deficit = pd.DataFrame({
    "Instancias Actuales": conteo,
    "Porcentaje (%)": porcentaje,
    "Faltante para 2.000": [max(0, N_OBJETIVO - c) for c in conteo],
    "Estado": ["Completo" if c >= N_OBJETIVO else "Deficitaria" for c in conteo]
})

print("\n" + "=" * 75)
print("DISTRIBUCIÓN Y DÉFICIT POR CATEGORÍA:")
print("=" * 75)
display(resumen_deficit)

total_faltante = sum([max(0, N_OBJETIVO - c) for c in conteo])
print(f"\n-> DÉFICIT ACUMULADO TOTAL: Faltan {total_faltante} instancias para balancear.")
print("-> JUSTIFICACIÓN: Se requiere ingesta masiva en Semantic Scholar (S2).")

# Métricas de longitud de contexto
df_master_real["num_palabras"] = df_master_real["citation_context"].astype(str).str.split().str.len()
print("\n" + "=" * 75)
print("LONGITUD PROMEDIO DE CONTEXTO (Palabras por categoría):")
print("=" * 75)
print(df_master_real.groupby("etiqueta_rescatada")["num_palabras"].agg(["mean", "min", "max"]).round(1))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
======================================================================
              REPORTE DE AUDITORÍA Y DISTRIBUCIÓN
======================================================================
Total registros clasificados: 25000
Total registros con error: 0

--- Valores nulos por columna ---
citation_context            0
rhetorical_section        519
citing_paper_id             0
cited_paper_id            109
cited_paper_title       25000
cited_paper_abstract     7686
source_dataset              0
index_original              0
predicted_label             0
scores_json                 0
dtype: int64

======================================================================
DISTRIBUCIÓN POR CATEGORÍA (Frecuencia Absoluta y Porcentual):
======================================================================

                                  Cantidad  Porcentaje (%)  Meta (2000)
predicted_label
Background                           17582           70.33     Completo
Application                           2970           11.88     Completo
Evidence                              1672            6.69   Faltan 328
Comparison                            1110            4.44   Faltan 890
Gap                                    470            1.88  Faltan 1530
Basis                                  455            1.82  Faltan 1545
Identification_of_the_Originator       402            1.61  Faltan 1598
Further_Reading                        237            0.95  Faltan 1763
Modification_Improvement               102            0.41  Faltan 1898

======================================================================
LONGITUD PROMEDIO DE CONTEXTO (Palabras por categoría):
======================================================================
                                  mean  min  max
predicted_label
Application                       26.7    6  161
Background                        19.9    6  219
Basis                             31.1    6  329
Comparison                        36.1    6  400
Evidence                          31.2    6  375
Further_Reading                   20.4    6  155
Gap                               34.6    7  407
Identification_of_the_Originator  26.4    6  145
Modification_Improvement          29.1    9  105

======================================================================
MUESTRA CUALITATIVA POR CATEGORÍA:
======================================================================

[CATEGORÍA: Background]
"Most primitive type of conducting cells and they are found in most of the seedless vascular plants and gymnosperms 2...."

[CATEGORÍA: Gap]
"The problem of obtaining genuine replicates in spatially connected systems such as rivers are difficult when the hypotheses aim to test ecological processes predicted to change alo..."

[CATEGORÍA: Basis]
"The mechanism of said reaction was studied and theorized to be isolobal to the disproportionation of metal-metal bonded dimers involving 19-valence electron intermediates...."

[CATEGORÍA: Comparison]
"In view of the results in rats and humans showing the FFA dependency of GSIS in the prolonged fasting state (18, 19, 42, 43) plus the very low fasting FFA levels caused by glucosei..."

[CATEGORÍA: Application]
"…allowing organisms to grow to arbitrarily large sizes (Andersen and Beyer 2006; Capitán and Delius 2010; Datta et al. 2011), a death rate that becomes large when organisms are lar..."

[CATEGORÍA: Modification_Improvement]
"Based on the definitions of the OISR tuple elements, we introduce an evaluation framework, which is a specialisation of the BWW evaluation framework [15,16] that is aimed at assess..."

[CATEGORÍA: Evidence]
"This assumption has been supported by recent work (46), and palmitate and oleate have long been considered optimal for modeling plasma FFA kinetics (25, 28, 29, 33, 46)...."

[CATEGORÍA: Identification_of_the_Originator]
"Yorkshire and Humber Biodiversity Forum LNU Recorders helped in the production of this Biodiversity Audit by providing some species information...."

[CATEGORÍA: Further_Reading]
"Handlist of Scientific Instrument- Maker's Trade Catalogs, 1600-1914;..."

## 7. Validación de Conectividad y Protocolo de Extracción en Semantic Scholar (S2)

En esta celda se implementa una prueba de concepto preliminar para verificar la comunicación con la API de Semantic Scholar antes de lanzar la ingesta a gran escala.

Las decisiones metodológicas de esta validación incluyen:
* **Verificación de autenticación y cuotas:** Comprobar que la clave de acceso (`S2_API_KEY`) sea reconocida y permita interactuar con los *endpoints* sin bloqueos ni errores de permisos.
* **Inspección del grafo académico:** Evaluar el flujo de recuperación en dos fases: búsqueda semántica de publicaciones relevantes (`/paper/search`) y posterior exploración de sus relaciones en el grafo de citas (`/paper/{paperId}/citations`).
* **Comprobación de la estructura de metadatos:** Corroborar que el servicio retorne efectivamente los contextos textuales de citación (`contexts`), las intenciones asignadas (`intents`) y los datos del documento citante (`citingPaper`), asegurando la viabilidad técnica para subsanar el déficit de clases minoritarias.

In [ ]:
# 1. Obtener API Key
S2_API_KEY = userdata.get('S2_API_KEY')

headers = {
    'x-api-key': S2_API_KEY
}

# 2. Prueba rápida: buscar un artículo y consultar sus contextos de citación
query = "transformer attention mechanism language models"
url_search = f"https://api.semanticscholar.org/graph/v1/paper/search?query={query}&limit=3&fields=paperId,title,abstract"

res = requests.get(url_search, headers=headers)
if res.status_code == 200:
    papers = res.json().get('data', [])
    print(f"¡Conexión exitosa a Semantic Scholar! Artículos encontrados: {len(papers)}")

    # Extraer citas del primer artículo
    if papers:
        paper_id = papers[0]['paperId']
        url_citations = f"https://api.semanticscholar.org/graph/v1/paper/{paper_id}/citations?limit=10&fields=contexts,intents,citingPaper.title"
        res_cit = requests.get(url_citations, headers=headers)
        if res_cit.status_code == 200:
            cits = res_cit.json().get('data', [])
            print(f"-> Contextos de cita extraídos de '{papers[0]['title'][:50]}...': {len(cits)}")
            for c in cits[:2]:
                print(f"   Contexto: {c.get('contexts', ['N/A'])[0] if c.get('contexts') else 'Sin contexto'}")
else:
    print(f"Error de conexión ({res.status_code}): {res.text}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
¡Conexión exitosa a Semantic Scholar! Artículos encontrados: 3
-> Contextos de cita extraídos de 'Analog in-memory computing attention mechanism for...': 10
   Contexto: Recently, ReRAM crossbars have attracted substantial academic and industrial interest as a promising platform for IMC realization [5], [6], due to their unique capability to directly map neural network weights onto the conductance states of memory cells.
   Contexto: Sin contexto

## 8. Ingesta Masiva Asíncrona con Semantic Scholar (S2) y Clasificación Guiada

En esta celda se ejecuta el pipeline de recolección masiva dirigida y clasificación para cerrar definitivamente el déficit en las categorías minoritarias.

Las decisiones metodológicas aplicadas en este flujo comprenden:

* **Diversificación temática multicontexto:** Se definen 12 disciplinas científicas amplias (modelos de difusión, biología computacional, optimización, grafos, etc.) para consultar publicaciones representativas, asegurando que la recolección de citas no quede sesgada por las convenciones discursivas de un único subcampo.
* **Recolección asíncrona no redundante:** Se utiliza un control de concurrencia acotado (`asyncio.Semaphore(3)`) y pausas adaptativas para respetar las limitaciones de tasa de Semantic Scholar. Asimismo, se descartan desde el inicio todos los contextos ya existentes en el archivo maestro o en checkpoints previos para optimizar llamadas a la API.
* **Alineación rigurosa con la guía de anotación:** La función de clasificación incorpora en el prompt del sistema las definiciones operativas formales de las 9 funciones retóricas. Esto guía a Gemini a discernir con precisión técnica diferencias sutiles (como el uso de herramientas sin cambio en *Application* versus adaptaciones en *Modification_Improvement*).
* **Esquema estructurado y tolerancia a fallos:** Se mantiene la exigencia del esquema JSON tipado mediante Pydantic y un esquema de reintentos con retroceso exponencial (*exponential backoff*), guardando lotes periódicos en Google Drive para preservar el avance ante cualquier interrupción de red.
* **Rescate probabilístico de alta sensibilidad:** Para las citas extraídas de S2, se aplica un umbral probabilístico adaptado sobre las clases minoritarias remanentes, promoviendo aquellas instancias con afinidad moderada o alta antes de consolidar la distribución final hacia la meta de balanceo (2.000 instancias por categoría).

In [ ]:
Python
# Rutas de trabajo y credenciales
os.makedirs(DRIVE_DIR, exist_ok=True)

archivo_master = os.path.join(DRIVE_DIR, "dataset_citas_reales_definitivo_master.csv")
checkpoint_masivo_s2 = os.path.join(DRIVE_DIR, "checkpoint_s2_ingesta_masiva_directa.csv")

S2_API_KEY = userdata.get('S2_API_KEY')
api_key_gemini = userdata.get('API_GEMINI')
client = genai.Client(api_key=api_key_gemini)

MODELO_A_USAR = "gemini-3.5-flash-lite"
N_OBJETIVO = 2000

CATEGORIAS = [
    "Background", "Gap", "Basis", "Comparison",
    "Application", "Modification_Improvement", "Evidence",
    "Identification_of_the_Originator", "Further_Reading"
]

# Revisamos qué citas ya tenemos para no repetir trabajo
df_master = pd.read_csv(archivo_master) if os.path.exists(archivo_master) else pd.DataFrame()
textos_existentes = set(df_master['citation_context'].astype(str)) if not df_master.empty else set()

if os.path.exists(checkpoint_masivo_s2):
    df_chk = pd.read_csv(checkpoint_masivo_s2)
    if 'citation_context' in df_chk.columns:
        textos_existentes.update(df_chk['citation_context'].astype(str))

# Términos de búsqueda en Semantic Scholar para cubrir varias áreas
DISCIPLINAS_AMPLIAS = [
    "transformer architecture language model",
    "convolutional neural network vision",
    "reinforcement learning policy optimization",
    "graph neural network representation",
    "contrastive learning self supervised",
    "diffusion models generative synthesis",
    "speech recognition audio acoustics",
    "computational biology genomics machine learning",
    "optimization stochastic gradient descent",
    "systematic review survey deep learning",
    "object detection semantic segmentation",
    "information retrieval dense embedding"
]

headers_s2 = {'x-api-key': S2_API_KEY}

# Descarga de contextos de cita para un paper específico
async def fetch_paper_citations(session, sem_s2, pid, title, domain):
    url_cits = f"https://api.semanticscholar.org/graph/v1/paper/{pid}/citations?limit=100&fields=contexts,citingPaper.title"
    async with sem_s2:
        for intento in range(3):
            try:
                async with session.get(url_cits, headers=headers_s2, timeout=25) as resp:
                    if resp.status == 200:
                        data = await resp.json()
                        cits = []
                        for item in data.get('data', []):
                            contexts = item.get('contexts', []) or []
                            citing_title = (item.get('citingPaper') or {}).get('title', 's2_paper')
                            for ctx in contexts:
                                txt = str(ctx).strip()
                                if len(txt.split()) >= 6:
                                    cits.append({
                                        'citation_context': txt,
                                        'rhetorical_section': f'Scientific Body ({domain})',
                                        'citing_paper_id': citing_title,
                                        'cited_paper_id': pid,
                                        'source_dataset': 'Semantic_Scholar_Async_Bulk'
                                    })
                        await asyncio.sleep(0.8)
                        return cits
                    elif resp.status == 429:
                        await asyncio.sleep((intento + 1) * 4)
                    else:
                        await asyncio.sleep(1.5)
            except Exception:
                await asyncio.sleep(1.5)
    return []

# Búsqueda de papers y recolección de citas en paralelo
async def recolectar_citas_s2():
    sem_s2 = asyncio.Semaphore(3)  # Límite de peticiones simultáneas a S2
    async with aiohttp.ClientSession() as session:
        print("1/3. Buscando artículos dinámicos en 12 áreas...")
        papers = []
        for disc in DISCIPLINAS_AMPLIAS:
            q_enc = urllib.parse.quote(disc)
            url_search = f"https://api.semanticscholar.org/graph/v1/paper/search?query={q_enc}&limit=35&fields=paperId,title"
            for intento in range(3):
                try:
                    async with session.get(url_search, headers=headers_s2, timeout=25) as r:
                        if r.status == 200:
                            data = await r.json()
                            for it in data.get('data', []):
                                if it.get('paperId'):
                                    papers.append((it['paperId'], it.get('title', 's2_paper'), disc))
                            await asyncio.sleep(1.0)
                            break
                        elif r.status == 429:
                            await asyncio.sleep((intento + 1) * 5)
                        else:
                            await asyncio.sleep(1.5)
                except Exception:
                    await asyncio.sleep(1.5)

        papers_unicos = list({p[0]: p for p in papers}.values())
        print(f" -> Total artículos recopilados: {len(papers_unicos)}")

        print("\n2/3. Descargando contextos de cita en paralelo...")
        tasks = [fetch_paper_citations(session, sem_s2, pid, title, domain) for pid, title, domain in papers_unicos]
        resultados = await asyncio.gather(*tasks)

        todas_citas = [cita for lista in resultados for cita in lista]
        return todas_citas

citas_raw = await recolectar_citas_s2()
df_nuevas = pd.DataFrame(citas_raw)

# Filtramos las que ya habíamos procesado antes
if not df_nuevas.empty:
    df_nuevas = df_nuevas[~df_nuevas['citation_context'].astype(str).isin(textos_existentes)].drop_duplicates(subset=['citation_context'])

print(f"\n-> Total citas auténticas nuevas listas para clasificar: {len(df_nuevas)}")

# Formato de respuesta estructurada que le pedimos a Gemini con Criterios de la Guía
class CitationClassification(BaseModel):
    Background: float = Field(description="0.0 a 1.0 según criterios de contexto general y revisión")
    Gap: float = Field(description="0.0 a 1.0 según identificación de limitaciones y vacíos")
    Basis: float = Field(description="0.0 a 1.0 según punto de partida teórico/conceptual o base fundacional")
    Comparison: float = Field(description="0.0 a 1.0 según contraste de resultados, datos o métodos")
    Application: float = Field(description="0.0 a 1.0 según uso directo sin modificación de herramientas/métodos")
    Modification_Improvement: float = Field(description="0.0 a 1.0 según adaptación o mejora metodológica")
    Evidence: float = Field(description="0.0 a 1.0 según soporte empírico, justificación de diseño o hallazgos")
    Identification_of_the_Originator: float = Field(description="0.0 a 1.0 según atribución de autoría original o pionera")
    Further_Reading: float = Field(description="0.0 a 1.0 según redirección a literatura complementaria")
    predicted_label: str = Field(description="Categoría única predominante")

# Clasificación de cada cita con manejo de reintentos y criterios de la guía
async def clasificar_registro(semaphore, index, texto, seccion, max_retries=5):
    async with semaphore:
        prompt = f"""You are an expert NLP annotator specializing in citation function classification.
Classify the following citation context strictly following these definition criteria:

1. Background: Provides context, historical development, general literature review, or broad overview of the field.
2. Gap: Highlights unexplored areas, limitations, shortcomings, unanswered questions, or what remains unknown.
3. Basis: Serves as the intellectual starting point, foundational premise, hypothesis, or theoretical foundation upon which the current work builds.
4. Comparison: Compares methodologies, findings, models, or performance between the current and cited work (similarities, differences, advantages).
5. Application: Directly applies or uses a method, tool, algorithm, formula, or dataset WITHOUT modification.
6. Modification_Improvement: Adapts, modifies, expands, or enhances existing methods, models, or tools to fit new conditions.
7. Evidence: Cites prior work to substantiate claims, support hypotheses, justify methodological designs, or validate empirical findings.
8. Identification_of_the_Originator: Formally credits the pioneer or original publication that first introduced a concept, algorithm, or theory.
9. Further_Reading: Explicitly directs readers to external/supplementary sources, tutorials, surveys, or extended documentation for deeper details.

Input Data:
- Rhetorical Section: {seccion}
- Citation Context: "{texto}"

Output requirements:
Assign a confidence score from 0.0 to 1.0 for each of the 9 categories and set 'predicted_label' to the single dominant category."""

        for attempt in range(max_retries):
            try:
                res = await client.aio.models.generate_content(
                    model=MODELO_A_USAR,
                    contents=prompt,
                    config=types.GenerateContentConfig(
                        response_mime_type="application/json",
                        response_schema=CitationClassification,
                        temperature=0.0
                    )
                )
                data = json.loads(res.text)
                label = data.get("predicted_label", "Background")
                if label not in CATEGORIAS:
                    label = max(
                        CATEGORIAS,
                        key=lambda c: (
                            data.get(c, 0.0)
                            if isinstance(data.get(c), (int, float))
                            else 0.0
                        )
                    )
                return index, label, data
            except Exception as e:
                wait_time = (2 ** attempt) + 1
                if any(err in str(e) for err in ["503", "429", "RESOURCE_EXHAUSTED", "UNAVAILABLE"]):
                    await asyncio.sleep(wait_time)
                else:
                    if attempt == max_retries - 1:
                        return index, "Error", {}
                    await asyncio.sleep(wait_time)
        return index, "Error", {}

# Envío por lotes para no saturar la API y guardar avances en Drive
async def ejecutar_pipeline(df_input, checkpoint_path, batch_size=150, max_concurrency=6):
    if df_input.empty:
        return pd.read_csv(checkpoint_path) if os.path.exists(checkpoint_path) else pd.DataFrame()

    semaphore = asyncio.Semaphore(max_concurrency)

    if os.path.exists(checkpoint_path):
        df_proc = pd.read_csv(checkpoint_path)
        textos_listos = set(df_proc['citation_context'].astype(str))
        df_pend = df_input[~df_input['citation_context'].astype(str).isin(textos_listos)].copy()
        print(f"Reanudando: {len(df_proc)} ya en checkpoint | {len(df_pend)} pendientes.")
    else:
        df_proc = pd.DataFrame()
        df_pend = df_input.copy()

    total = len(df_pend)
    if total == 0:
        return df_proc

    print(f"\n3/3. Clasificando {total} citas con Gemini (Guardado en Drive por lote)...")
    for i in range(0, total, batch_size):
        batch = df_pend.iloc[i:i+batch_size]
        tasks = [
            clasificar_registro(
                semaphore,
                idx,
                row['citation_context'],
                row.get('rhetorical_section', 'Scientific Body')
            )
            for idx, row in batch.iterrows()
        ]
        print(f"Procesando lote {i//batch_size + 1}/{(total + batch_size - 1)//batch_size}...")
        respuestas = await asyncio.gather(*tasks)

        nuevos = []
        for idx, label, scores in respuestas:
            if label != "Error":
                fila = batch.loc[idx].to_dict()
                fila['predicted_label'] = label
                fila['scores_json'] = json.dumps(scores)
                nuevos.append(fila)

        if nuevos:
            df_proc = pd.concat([df_proc, pd.DataFrame(nuevos)], ignore_index=True)
            df_proc.to_csv(checkpoint_path, index=False)
            print(f" -> Checkpoint guardado en Drive ({len(df_proc)} acumulados).")

    return df_proc

df_clasificados = await ejecutar_pipeline(df_nuevas, checkpoint_masivo_s2)

# Rescate de clases con pocos ejemplos usando las probabilidades de Gemini
def rescate_profundo(row):
    label = row.get("predicted_label", "Background")
    clases_escasas = ["Modification_Improvement", "Further_Reading", "Gap", "Basis", "Comparison"]
    if label in clases_escasas:
        return label
    try:
        scores = json.loads(row["scores_json"])
        for cat in clases_escasas:
            if float(scores.get(cat, 0.0)) >= 0.28:
                return cat
        mejor = max(clases_escasas, key=lambda c: float(scores.get(c, 0.0)))
        if float(scores.get(mejor, 0.0)) >= 0.18:
            return mejor
    except:
        pass
    return label

# Consolidamos todo lo nuevo en el archivo maestro
if not df_clasificados.empty:
    df_clasificados["etiqueta_rescatada"] = df_clasificados.apply(rescate_profundo, axis=1)
    if 'rhetorical_section' not in df_clasificados.columns:
        df_clasificados['rhetorical_section'] = 'Scientific Body'

    df_master_actualizado = pd.concat([
        df_master[['citation_context', 'rhetorical_section', 'etiqueta_rescatada']],
        df_clasificados[['citation_context', 'rhetorical_section', 'etiqueta_rescatada']]
    ], ignore_index=True).drop_duplicates(subset=['citation_context'])

    df_master_actualizado.to_csv(archivo_master, index=False)
else:
    df_master_actualizado = df_master.copy()

# Estado final tras la extracción
print("\n" + "=" * 60)
print("DISTRIBUCIÓN TOTAL MASTER TRAS EXTRACCIÓN MASIVA:")
print("=" * 60)
conteo = df_master_actualizado['etiqueta_rescatada'].value_counts()
resumen = pd.DataFrame({
    'Instancias Reales': conteo,
    'Faltante para 2.000': [max(0, N_OBJETIVO - c) for c in conteo]
})
display(resumen)
print(f"\nDéficit total restante hacia los 18.000: {sum(resumen['Faltante para 2.000'])}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
1/3. Buscando artículos dinámicos en 12 áreas...
 -> Total artículos recopilados: 350

2/3. Descargando contextos de cita en paralelo...

-> Total citas auténticas nuevas listas para clasificar: 15679

3/3. Clasificando 15679 citas con Gemini (Guardado en Drive por lote)...
Procesando lote 1/105...
 -> Checkpoint guardado en Drive (150 acumulados).
Procesando lote 2/105...
 -> Checkpoint guardado en Drive (300 acumulados).
Procesando lote 3/105...
 -> Checkpoint guardado en Drive (450 acumulados).
Procesando lote 4/105...
 -> Checkpoint guardado en Drive (600 acumulados).
Procesando lote 5/105...
 -> Checkpoint guardado en Drive (750 acumulados).
Procesando lote 6/105...
 -> Checkpoint guardado en Drive (900 acumulados).
Procesando lote 7/105...
 -> Checkpoint guardado en Drive (1050 acumulados).
Procesando lote 8/105...
 -> Checkpoint guardado en Drive (1200 acumulados).
Procesando lote 9/105...
 -> Checkpoint guardado en Drive (1350 acumulados).
Procesando lote 10/105...
 -> Checkpoint guardado en Drive (1500 acumulados).
Procesando lote 11/105...
 -> Checkpoint guardado en Drive (1650 acumulados).
Procesando lote 12/105...
 -> Checkpoint guardado en Drive (1800 acumulados).
Procesando lote 13/105...
 -> Checkpoint guardado en Drive (1950 acumulados).
Procesando lote 14/105...
 -> Checkpoint guardado en Drive (2100 acumulados).
Procesando lote 15/105...
 -> Checkpoint guardado en Drive (2250 acumulados).
Procesando lote 16/105...
 -> Checkpoint guardado en Drive (2400 acumulados).
Procesando lote 17/105...
 -> Checkpoint guardado en Drive (2550 acumulados).
Procesando lote 18/105...
 -> Checkpoint guardado en Drive (2700 acumulados).
Procesando lote 19/105...
 -> Checkpoint guardado en Drive (2850 acumulados).
Procesando lote 20/105...
 -> Checkpoint guardado en Drive (3000 acumulados).
Procesando lote 21/105...
 -> Checkpoint guardado en Drive (3150 acumulados).
Procesando lote 22/105...
 -> Checkpoint guardado en Drive (3300 acumulados).
Procesando lote 23/105...
 -> Checkpoint guardado en Drive (3450 acumulados).
Procesando lote 24/105...
 -> Checkpoint guardado en Drive (3600 acumulados).
Procesando lote 25/105...
 -> Checkpoint guardado en Drive (3750 acumulados).
Procesando lote 26/105...
 -> Checkpoint guardado en Drive (3900 acumulados).
Procesando lote 27/105...
 -> Checkpoint guardado en Drive (4050 acumulados).
Procesando lote 28/105...
 -> Checkpoint guardado en Drive (4200 acumulados).
Procesando lote 29/105...
 -> Checkpoint guardado en Drive (4350 acumulados).
Procesando lote 30/105...
 -> Checkpoint guardado en Drive (4500 acumulados).
Procesando lote 31/105...
 -> Checkpoint guardado en Drive (4650 acumulados).
Procesando lote 32/105...
 -> Checkpoint guardado en Drive (4800 acumulados).
Procesando lote 33/105...
 -> Checkpoint guardado en Drive (4950 acumulados).
Procesando lote 34/105...
 -> Checkpoint guardado en Drive (5100 acumulados).
Procesando lote 35/105...
 -> Checkpoint guardado en Drive (5250 acumulados).
Procesando lote 36/105...
 -> Checkpoint guardado en Drive (5400 acumulados).
Procesando lote 37/105...
 -> Checkpoint guardado en Drive (5550 acumulados).
Procesando lote 38/105...
 -> Checkpoint guardado en Drive (5700 acumulados).
Procesando lote 39/105...
 -> Checkpoint guardado en Drive (5850 acumulados).
Procesando lote 40/105...
 -> Checkpoint guardado en Drive (6000 acumulados).
Procesando lote 41/105...
 -> Checkpoint guardado en Drive (6150 acumulados).
Procesando lote 42/105...
 -> Checkpoint guardado en Drive (6300 acumulados).
Procesando lote 43/105...
 -> Checkpoint guardado en Drive (6450 acumulados).
Procesando lote 44/105...
 -> Checkpoint guardado en Drive (6600 acumulados).
Procesando lote 45/105...
 -> Checkpoint guardado en Drive (6750 acumulados).
Procesando lote 46/105...
 -> Checkpoint guardado en Drive (6900 acumulados).
Procesando lote 47/105...
 -> Checkpoint guardado en Drive (7050 acumulados).
Procesando lote 48/105...
 -> Checkpoint guardado en Drive (7200 acumulados).
Procesando lote 49/105...
 -> Checkpoint guardado en Drive (7350 acumulados).
Procesando lote 50/105...
 -> Checkpoint guardado en Drive (7500 acumulados).
Procesando lote 51/105...
 -> Checkpoint guardado en Drive (7650 acumulados).
Procesando lote 52/105...
 -> Checkpoint guardado en Drive (7800 acumulados).
Procesando lote 53/105...
 -> Checkpoint guardado en Drive (7950 acumulados).
Procesando lote 54/105...
 -> Checkpoint guardado en Drive (8100 acumulados).
Procesando lote 55/105...
 -> Checkpoint guardado en Drive (8250 acumulados).
Procesando lote 56/105...
 -> Checkpoint guardado en Drive (8400 acumulados).
Procesando lote 57/105...
 -> Checkpoint guardado en Drive (8550 acumulados).
Procesando lote 58/105...
 -> Checkpoint guardado en Drive (8700 acumulados).
Procesando lote 59/105...
 -> Checkpoint guardado en Drive (8850 acumulados).
Procesando lote 60/105...
 -> Checkpoint guardado en Drive (9000 acumulados).
Procesando lote 61/105...
 -> Checkpoint guardado en Drive (9150 acumulados).
Procesando lote 62/105...
 -> Checkpoint guardado en Drive (9300 acumulados).
Procesando lote 63/105...
 -> Checkpoint guardado en Drive (9450 acumulados).
Procesando lote 64/105...
 -> Checkpoint guardado en Drive (9600 acumulados).
Procesando lote 65/105...
 -> Checkpoint guardado en Drive (9750 acumulados).
Procesando lote 66/105...
 -> Checkpoint guardado en Drive (9900 acumulados).
Procesando lote 67/105...
 -> Checkpoint guardado en Drive (10050 acumulados).
Procesando lote 68/105...
 -> Checkpoint guardado en Drive (10200 acumulados).
Procesando lote 69/105...
 -> Checkpoint guardado en Drive (10350 acumulados).
Procesando lote 70/105...
 -> Checkpoint guardado en Drive (10500 acumulados).
Procesando lote 71/105...
 -> Checkpoint guardado en Drive (10650 acumulados).
Procesando lote 72/105...
 -> Checkpoint guardado en Drive (10800 acumulados).
Procesando lote 73/105...
 -> Checkpoint guardado en Drive (10950 acumulados).
Procesando lote 74/105...
 -> Checkpoint guardado en Drive (11100 acumulados).
Procesando lote 75/105...
 -> Checkpoint guardado en Drive (11250 acumulados).
Procesando lote 76/105...
 -> Checkpoint guardado en Drive (11400 acumulados).
Procesando lote 77/105...
 -> Checkpoint guardado en Drive (11550 acumulados).
Procesando lote 78/105...
 -> Checkpoint guardado en Drive (11700 acumulados).
Procesando lote 79/105...
 -> Checkpoint guardado en Drive (11850 acumulados).
Procesando lote 80/105...
 -> Checkpoint guardado en Drive (12000 acumulados).
Procesando lote 81/105...
 -> Checkpoint guardado en Drive (12150 acumulados).
Procesando lote 82/105...
 -> Checkpoint guardado en Drive (12300 acumulados).
Procesando lote 83/105...
 -> Checkpoint guardado en Drive (12450 acumulados).
Procesando lote 84/105...
 -> Checkpoint guardado en Drive (12600 acumulados).
Procesando lote 85/105...
 -> Checkpoint guardado en Drive (12750 acumulados).
Procesando lote 86/105...
 -> Checkpoint guardado en Drive (12900 acumulados).
Procesando lote 87/105...
 -> Checkpoint guardado en Drive (13050 acumulados).
Procesando lote 88/105...
 -> Checkpoint guardado en Drive (13200 acumulados).
Procesando lote 89/105...
 -> Checkpoint guardado en Drive (13350 acumulados).
Procesando lote 90/105...
 -> Checkpoint guardado en Drive (13500 acumulados).
Procesando lote 91/105...
 -> Checkpoint guardado en Drive (13650 acumulados).
Procesando lote 92/105...
 -> Checkpoint guardado en Drive (13800 acumulados).
Procesando lote 93/105...
 -> Checkpoint guardado en Drive (13950 acumulados).
Procesando lote 94/105...
 -> Checkpoint guardado en Drive (14100 acumulados).
Procesando lote 95/105...
 -> Checkpoint guardado en Drive (14250 acumulados).
Procesando lote 96/105...
 -> Checkpoint guardado en Drive (14400 acumulados).
Procesando lote 97/105...
 -> Checkpoint guardado en Drive (14550 acumulados).
Procesando lote 98/105...
 -> Checkpoint guardado en Drive (14700 acumulados).
Procesando lote 99/105...
 -> Checkpoint guardado en Drive (14850 acumulados).
Procesando lote 100/105...
 -> Checkpoint guardado en Drive (15000 acumulados).
Procesando lote 101/105...
 -> Checkpoint guardado en Drive (15150 acumulados).
Procesando lote 102/105...
 -> Checkpoint guardado en Drive (15300 acumulados).
Procesando lote 103/105...
 -> Checkpoint guardado en Drive (15450 acumulados).
Procesando lote 104/105...
 -> Checkpoint guardado en Drive (15600 acumulados).
Procesando lote 105/105...
 -> Checkpoint guardado en Drive (15679 acumulados).

============================================================
DISTRIBUCIÓN TOTAL MASTER TRAS EXTRACCIÓN MASIVA:
============================================================

                                  Instancias Reales  Faltante para 2.000
etiqueta_rescatada
Background                                    15616                    0
Comparison                                     5027                    0
Basis                                          4887                    0
Evidence                                       4112                    0
Further_Reading                                3837                    0
Identification_of_the_Originator               3035                    0
Gap                                            2596                    0
Application                                    2464                    0
Modification_Improvement                       2225                    0

Déficit total restante hacia los 18.000: 0

### 9. Ingesta Dirigida y Clasificación Focalizada de Brechas

**¿Por qué se implementa este paso?**

* **Mitigar el sobreajuste (*overfitting*):** Las clases discursivas minoritarias (como `Modification_Improvement` y `Application`) suelen presentar una frecuencia natural muy baja en los artículos científicos. Si se entrena el modelo con un conjunto reducido de estas instancias, existe un alto riesgo de que memorice patrones léxicos superficiales y expresiones específicas de unos pocos autores en lugar de aprender la función retórica real.
* **Aumentar la diversidad y representatividad del corpus:** Incrementar deliberadamente el volumen de citas auténticas en las categorías rezagadas enriquece la variabilidad estructural, sintáctica y de vocabulario del conjunto de datos. Esta mayor densidad de ejemplos robustece el espacio de representación latente antes de la fase de entrenamiento y evaluación.
* **Preservar el balance sin introducir sesgos artificiales:** En lugar de recurrir a técnicas como el sobremuestreo repetitivo o la generación sintética —las cuales no aportan información semántica nueva o inducen sesgos predecibles—, la extracción activa de citas reales inéditas amplía el soporte empírico del dataset manteniendo una distribución homogénea en todas las clases.
* **Maximizar la capacidad de generalización:** Un conjunto de datos con un volumen mayor y representativo por categoría permite que el clasificador generalice con mayor precisión frente a literatura científica no vista, mejorando directamente su desempeño en contextos metodológicos complejos y sutiles.o el balanceo exacto requerido antes de la partición final.

In [15]:
# 1. Configuración, Credenciales y Rutas
os.makedirs(DRIVE_DIR, exist_ok=True)
archivo_master = os.path.join(DRIVE_DIR, "dataset_citas_reales_definitivo_master.csv")
checkpoint_cierre = os.path.join(DRIVE_DIR, "checkpoint_s2_cierre_2500.csv")

S2_API_KEY = userdata.get('S2_API_KEY')
api_key_gemini = userdata.get('API_GEMINI')
client = genai.Client(api_key=api_key_gemini)

MODELO_A_USAR = "gemini-3.5-flash-lite"
N_OBJETIVO = 2500
CATEGORIAS = [
    "Background", "Gap", "Basis", "Comparison",
    "Application", "Modification_Improvement", "Evidence",
    "Identification_of_the_Originator", "Further_Reading"
]
headers_s2 = {'x-api-key': S2_API_KEY}

# 2. Control de Existencias
df_master = pd.read_csv(archivo_master) if os.path.exists(archivo_master) else pd.DataFrame()
textos_existentes = set(df_master['citation_context'].astype(str)) if not df_master.empty else set()
papers_ya_procesados = set(df_master['cited_paper_id'].astype(str)) if ('cited_paper_id' in df_master.columns and not df_master.empty) else set()

if os.path.exists(checkpoint_cierre):
    df_chk = pd.read_csv(checkpoint_cierre)
    if 'citation_context' in df_chk.columns:
        textos_existentes.update(df_chk['citation_context'].astype(str))

# 3. Consultas Focalizadas para Semantic Scholar
DISCIPLINAS_EXTRA = [
    "we modify the architecture extend framework",
    "adapted from variant proposed improvement",
    "extended the loss function fine tuned model",
    "implementation modified version algorithm",
    "improved baseline modified approach network",
    "we employ the library utilize tool dataset",
    "adapted the method to our setting pipeline"
]

class CitationClassification(BaseModel):
    Background: float = Field(description="0.0 a 1.0 según criterios de contexto general y revisión")
    Gap: float = Field(description="0.0 a 1.0 según identificación de limitaciones y vacíos")
    Basis: float = Field(description="0.0 a 1.0 según punto de partida teórico/conceptual o base fundacional")
    Comparison: float = Field(description="0.0 a 1.0 según contraste de resultados, datos o métodos")
    Application: float = Field(description="0.0 a 1.0 según uso directo sin modificación de herramientas/métodos")
    Modification_Improvement: float = Field(description="0.0 a 1.0 según adaptación o mejora metodológica")
    Evidence: float = Field(description="0.0 a 1.0 según soporte empírico, justificación de diseño o hallazgos")
    Identification_of_the_Originator: float = Field(description="0.0 a 1.0 según atribución de autoría original o pionera")
    Further_Reading: float = Field(description="0.0 a 1.0 según redirección a literatura complementaria")
    predicted_label: str = Field(description="Categoría única predominante")

def rescate_profundo(row):
    label = row.get("predicted_label", "Background")
    clases_escasas = ["Modification_Improvement", "Application", "Gap", "Basis", "Comparison"]
    if label in clases_escasas:
        return label
    try:
        scores = json.loads(row["scores_json"])
        for cat in clases_escasas:
            if float(scores.get(cat, 0.0)) >= 0.28:
                return cat
        mejor = max(clases_escasas, key=lambda c: float(scores.get(c, 0.0)))
        if float(scores.get(mejor, 0.0)) >= 0.18:
            return mejor
    except Exception:
        pass
    return label

# 4. Extracción Asíncrona S2
async def fetch_paper_citations(session, sem_s2, pid, title, domain):
    url_cits = f"https://api.semanticscholar.org/graph/v1/paper/{pid}/citations?limit=100&fields=contexts,citingPaper.title"
    async with sem_s2:
        for intento in range(3):
            try:
                async with session.get(url_cits, headers=headers_s2, timeout=25) as resp:
                    if resp.status == 200:
                        data = await resp.json()
                        cits = []
                        for item in data.get('data', []):
                            contexts = item.get('contexts', []) or []
                            citing_title = (item.get('citingPaper') or {}).get('title', 's2_paper')
                            for ctx in contexts:
                                txt = str(ctx).strip()
                                if len(txt.split()) >= 6:
                                    cits.append({
                                        'citation_context': txt,
                                        'rhetorical_section': f'Scientific Body ({domain})',
                                        'citing_paper_id': citing_title,
                                        'cited_paper_id': pid
                                    })
                        await asyncio.sleep(0.8)
                        return cits
                    elif resp.status == 429:
                        await asyncio.sleep((intento + 1) * 4)
                    else:
                        await asyncio.sleep(1.5)
            except Exception:
                await asyncio.sleep(1.5)
    return []

async def recolectar_s2():
    sem_s2 = asyncio.Semaphore(3)
    async with aiohttp.ClientSession() as session:
        print("1/3. Buscando artículos metodológicos en S2...", flush=True)
        papers = []
        for disc in DISCIPLINAS_EXTRA:
            q_enc = urllib.parse.quote(disc)
            url_search = f"https://api.semanticscholar.org/graph/v1/paper/search?query={q_enc}&limit=40&fields=paperId,title"
            for intento in range(3):
                try:
                    async with session.get(url_search, headers=headers_s2, timeout=25) as r:
                        if r.status == 200:
                            data = await r.json()
                            for it in data.get('data', []):
                                pid = it.get('paperId')
                                if pid and pid not in papers_ya_procesados:
                                    papers.append((pid, it.get('title', 's2_paper'), disc))
                            await asyncio.sleep(1.0)
                            break
                        elif r.status == 429:
                            await asyncio.sleep((intento + 1) * 4)
                        else:
                            await asyncio.sleep(1.5)
                except Exception:
                    await asyncio.sleep(1.5)

        papers_unicos = list({p[0]: p for p in papers}.values())
        print(f" -> Papers nuevos recopilados: {len(papers_unicos)}", flush=True)

        print("2/3. Descargando contextos de cita...", flush=True)
        tasks = [fetch_paper_citations(session, sem_s2, pid, title, domain) for pid, title, domain in papers_unicos]
        resultados = await asyncio.gather(*tasks)
        return [cita for lista in resultados for cita in lista]

# Descargar y filtrar
citas_raw = await recolectar_s2()
df_nuevas = pd.DataFrame(citas_raw)
if not df_nuevas.empty:
    df_nuevas = df_nuevas[~df_nuevas['citation_context'].astype(str).isin(textos_existentes)].drop_duplicates(subset=['citation_context'])

PATRON_FILTRO = re.compile(
    r'\b(?:modifi|extend|adapt|improv|enhanc|variant|alter|adjust|replac|appli|utiliz|employ|implement|tool|packag|librar)\b',
    re.IGNORECASE
)
df_candidatas = df_nuevas[df_nuevas['citation_context'].str.contains(PATRON_FILTRO, regex=True)].copy() if not df_nuevas.empty else pd.DataFrame()
print(f" -> Citas candidatas filtradas: {len(df_candidatas)}", flush=True)

# 5. Clasificación Síncrona Estable con Gemini 3.5 Flash
print(f"\n3/3. Clasificando con {MODELO_A_USAR}...", flush=True)

if os.path.exists(checkpoint_cierre):
    df_proc = pd.read_csv(checkpoint_cierre)
    textos_listos = set(df_proc['citation_context'].astype(str))
    df_pend = df_candidatas[~df_candidatas['citation_context'].astype(str).isin(textos_listos)].copy()
else:
    df_proc = pd.DataFrame()
    df_pend = df_candidatas.copy()

conteo_temp = df_master['etiqueta_rescatada'].value_counts().to_dict() if not df_master.empty else {}
if not df_proc.empty and 'etiqueta_rescatada' in df_proc.columns:
    for cat, val in df_proc['etiqueta_rescatada'].value_counts().items():
        conteo_temp[cat] = conteo_temp.get(cat, 0) + val

buffer_salvado = []
for idx_num, (idx, row) in enumerate(df_pend.iterrows(), 1):
    if conteo_temp.get('Modification_Improvement', 0) >= N_OBJETIVO and conteo_temp.get('Application', 0) >= N_OBJETIVO:
        print("\n-> ¡Meta alcanzada en clases prioritarias! Finalizando.", flush=True)
        break

    txt = row['citation_context']
    sec = row.get('rhetorical_section', 'Scientific Body')

    prompt = f"""You are an expert NLP annotator specializing in citation function classification.
Classify the following citation context strictly following these definition criteria:
1. Background: General context or overview.
2. Gap: Highlights limitations or unanswered questions.
3. Basis: Foundational premise or theoretical basis.
4. Comparison: Compares methodologies, findings, or metrics.
5. Application: Applies tools or methods WITHOUT modification.
6. Modification_Improvement: Adapts, modifies, or enhances methods.
7. Evidence: Substantiates claims or validates findings.
8. Identification_of_the_Originator: Credits pioneer work.
9. Further_Reading: Directs to external tutorials or surveys.

Input:
- Section: {sec}
- Context: "{txt}"

Output requirements:
Assign a confidence score from 0.0 to 1.0 for each of the 9 categories and set 'predicted_label' to the dominant category."""

    exito = False
    for intento in range(3):
        try:
            res = client.models.generate_content(
                model=MODELO_A_USAR,
                contents=prompt,
                config=types.GenerateContentConfig(
                    response_mime_type="application/json",
                    response_schema=CitationClassification,
                    temperature=0.0
                )
            )
            data = json.loads(res.text)
            label = data.get("predicted_label", "Background")
            if label not in CATEGORIAS:
                label = max(CATEGORIAS, key=lambda c: data.get(c, 0.0) if isinstance(data.get(c), (int, float)) else 0.0)

            fila = row.to_dict()
            fila['predicted_label'] = label
            fila['scores_json'] = json.dumps(data)
            label_final = rescate_profundo(fila)
            fila['etiqueta_rescatada'] = label_final
            buffer_salvado.append(fila)

            conteo_temp[label_final] = conteo_temp.get(label_final, 0) + 1
            print(f"[{idx_num:3d}/{len(df_pend)}] {label_final:25s} | Mod_Imp: {conteo_temp.get('Modification_Improvement', 0)}/{N_OBJETIVO}", flush=True)
            exito = True
            break
        except Exception as e:
            time.sleep(2 * (intento + 1) if any(err in str(e) for err in ["503", "429"]) else 1.5)

    if len(buffer_salvado) >= 5:
        df_proc = pd.concat([df_proc, pd.DataFrame(buffer_salvado)], ignore_index=True)
        df_proc.to_csv(checkpoint_cierre, index=False)
        buffer_salvado = []

    time.sleep(0.4)

if buffer_salvado:
    df_proc = pd.concat([df_proc, pd.DataFrame(buffer_salvado)], ignore_index=True)
    df_proc.to_csv(checkpoint_cierre, index=False)

# 6. Consolidación Final en Master
if not df_proc.empty:
    cols = ['citation_context', 'rhetorical_section', 'etiqueta_rescatada', 'cited_paper_id', 'citing_paper_id']
    for c in cols:
        if c not in df_master.columns: df_master[c] = f"{c}_legacy"
        if c not in df_proc.columns: df_proc[c] = f"{c}_new"

    df_master = pd.concat([df_master[cols], df_proc[cols]], ignore_index=True).drop_duplicates(subset=['citation_context'])
    df_master.to_csv(archivo_master, index=False)

print("\n-> Proceso consolidado exitosamente en el archivo maestro.")

-> Usando modelo principal: gemini-3.5-flash
Reanudando: 13 ya en checkpoint | 300 pendientes.
Iniciando procesamiento de 300 citas candidatas con gemini-3.5-flash...

[  1/300] Falló registro tras 3 intentos. Continuando...
[  2/300] Asignada: Background                | Mod_Imp: 2268/2500 | App: 2497/2500
[  3/300] Asignada: Gap                       | Mod_Imp: 2268/2500 | App: 2497/2500
[  4/300] Asignada: Gap                       | Mod_Imp: 2268/2500 | App: 2497/2500
   💾 Checkpoint actualizado en Drive (16 acumuladas)

[  5/300] Asignada: Basis                     | Mod_Imp: 2268/2500 | App: 2497/2500
[  6/300] Asignada: Application               | Mod_Imp: 2268/2500 | App: 2498/2500
[  7/300] Asignada: Application               | Mod_Imp: 2268/2500 | App: 2499/2500
   💾 Checkpoint actualizado en Drive (19 acumuladas)

[  8/300] Asignada: Modification_Improvement  | Mod_Imp: 2269/2500 | App: 2499/2500
[  9/300] Asignada: Basis                     | Mod_Imp: 2269/2500 | App: 2499/2500
[ 10/300] Asignada: Modification_Improvement  | Mod_Imp: 2270/2500 | App: 2499/2500
   💾 Checkpoint actualizado en Drive (22 acumuladas)

[ 11/300] Asignada: Modification_Improvement  | Mod_Imp: 2271/2500 | App: 2499/2500
[ 12/300] Asignada: Application               | Mod_Imp: 2271/2500 | App: 2500/2500
[ 13/300] Asignada: Modification_Improvement  | Mod_Imp: 2272/2500 | App: 2500/2500
   💾 Checkpoint actualizado en Drive (25 acumuladas)

[ 14/300] Asignada: Comparison                | Mod_Imp: 2272/2500 | App: 2500/2500
[ 15/300] Asignada: Background                | Mod_Imp: 2272/2500 | App: 2500/2500
[ 16/300] Asignada: Identification_of_the_Originator | Mod_Imp: 2272/2500 | App: 2500/2500
   💾 Checkpoint actualizado en Drive (28 acumuladas)

[ 17/300] Asignada: Modification_Improvement  | Mod_Imp: 2273/2500 | App: 2500/2500
[ 18/300] Asignada: Gap                       | Mod_Imp: 2273/2500 | App: 2500/2500
[ 19/300] Asignada: Background                | Mod_Imp: 2273/2500 | App: 2500/2500
   💾 Checkpoint actualizado en Drive (31 acumuladas)

[ 20/300] Asignada: Modification_Improvement  | Mod_Imp: 2274/2500 | App: 2500/2500
[ 21/300] Asignada: Modification_Improvement  | Mod_Imp: 2275/2500 | App: 2500/2500
[ 22/300] Asignada: Background                | Mod_Imp: 2275/2500 | App: 2500/2500
   💾 Checkpoint actualizado en Drive (34 acumuladas)

[ 23/300] Asignada: Modification_Improvement  | Mod_Imp: 2276/2500 | App: 2500/2500
[ 24/300] Asignada: Background                | Mod_Imp: 2276/2500 | App: 2500/2500
[ 25/300] Asignada: Basis                     | Mod_Imp: 2276/2500 | App: 2500/2500
   💾 Checkpoint actualizado en Drive (37 acumuladas)

[ 26/300] Asignada: Further_Reading           | Mod_Imp: 2276/2500 | App: 2500/2500
[ 27/300] Asignada: Modification_Improvement  | Mod_Imp: 2277/2500 | App: 2500/2500
[ 28/300] Asignada: Comparison                | Mod_Imp: 2277/2500 | App: 2500/2500
   💾 Checkpoint actualizado en Drive (40 acumuladas)

[ 29/300] Asignada: Comparison                | Mod_Imp: 2277/2500 | App: 2500/2500
[ 30/300] Asignada: Application               | Mod_Imp: 2277/2500 | App: 2501/2500
[ 31/300] Asignada: Comparison                | Mod_Imp: 2277/2500 | App: 2501/2500
   💾 Checkpoint actualizado en Drive (43 acumuladas)

[ 32/300] Asignada: Application               | Mod_Imp: 2277/2500 | App: 2502/2500
[ 33/300] Asignada: Application               | Mod_Imp: 2277/2500 | App: 2503/2500
[ 34/300] Asignada: Application               | Mod_Imp: 2277/2500 | App: 2504/2500
   💾 Checkpoint actualizado en Drive (46 acumuladas)

[ 35/300] Asignada: Application               | Mod_Imp: 2277/2500 | App: 2505/2500
[ 36/300] Asignada: Application               | Mod_Imp: 2277/2500 | App: 2506/2500
[ 37/300] Asignada: Modification_Improvement  | Mod_Imp: 2278/2500 | App: 2506/2500
   💾 Checkpoint actualizado en Drive (49 acumuladas)

[ 38/300] Asignada: Application               | Mod_Imp: 2278/2500 | App: 2507/2500
[ 39/300] Asignada: Application               | Mod_Imp: 2278/2500 | App: 2508/2500
[ 40/300] Asignada: Comparison                | Mod_Imp: 2278/2500 | App: 2508/2500
   💾 Checkpoint actualizado en Drive (52 acumuladas)

[ 41/300] Asignada: Background                | Mod_Imp: 2278/2500 | App: 2508/2500
[ 42/300] Asignada: Evidence                  | Mod_Imp: 2278/2500 | App: 2508/2500
[ 43/300] Asignada: Modification_Improvement  | Mod_Imp: 2279/2500 | App: 2508/2500
   💾 Checkpoint actualizado en Drive (55 acumuladas)

[ 44/300] Asignada: Modification_Improvement  | Mod_Imp: 2280/2500 | App: 2508/2500
[ 45/300] Asignada: Identification_of_the_Originator | Mod_Imp: 2280/2500 | App: 2508/2500
[ 46/300] Asignada: Basis                     | Mod_Imp: 2280/2500 | App: 2508/2500
   💾 Checkpoint actualizado en Drive (58 acumuladas)

[ 47/300] Asignada: Modification_Improvement  | Mod_Imp: 2281/2500 | App: 2508/2500
[ 48/300] Asignada: Application               | Mod_Imp: 2281/2500 | App: 2509/2500
[ 49/300] Asignada: Evidence                  | Mod_Imp: 2281/2500 | App: 2509/2500
   💾 Checkpoint actualizado en Drive (61 acumuladas)

[ 50/300] Asignada: Basis                     | Mod_Imp: 2281/2500 | App: 2509/2500
[ 51/300] Asignada: Gap                       | Mod_Imp: 2281/2500 | App: 2509/2500
[ 52/300] Asignada: Background                | Mod_Imp: 2281/2500 | App: 2509/2500
   💾 Checkpoint actualizado en Drive (64 acumuladas)

[ 53/300] Asignada: Modification_Improvement  | Mod_Imp: 2282/2500 | App: 2509/2500
[ 54/300] Asignada: Basis                     | Mod_Imp: 2282/2500 | App: 2509/2500
[ 55/300] Asignada: Evidence                  | Mod_Imp: 2282/2500 | App: 2509/2500
   💾 Checkpoint actualizado en Drive (67 acumuladas)

[ 56/300] Asignada: Comparison                | Mod_Imp: 2282/2500 | App: 2509/2500
[ 57/300] Asignada: Application               | Mod_Imp: 2282/2500 | App: 2510/2500
[ 58/300] Asignada: Background                | Mod_Imp: 2282/2500 | App: 2510/2500
   💾 Checkpoint actualizado en Drive (70 acumuladas)

[ 59/300] Asignada: Application               | Mod_Imp: 2282/2500 | App: 2511/2500
[ 60/300] Asignada: Modification_Improvement  | Mod_Imp: 2283/2500 | App: 2511/2500
[ 61/300] Asignada: Application               | Mod_Imp: 2283/2500 | App: 2512/2500
   💾 Checkpoint actualizado en Drive (73 acumuladas)

[ 62/300] Asignada: Comparison                | Mod_Imp: 2283/2500 | App: 2512/2500
[ 63/300] Asignada: Comparison                | Mod_Imp: 2283/2500 | App: 2512/2500
[ 64/300] Asignada: Identification_of_the_Originator | Mod_Imp: 2283/2500 | App: 2512/2500
   💾 Checkpoint actualizado en Drive (76 acumuladas)

[ 65/300] Asignada: Comparison                | Mod_Imp: 2283/2500 | App: 2512/2500
[ 66/300] Asignada: Comparison                | Mod_Imp: 2283/2500 | App: 2512/2500
[ 67/300] Asignada: Application               | Mod_Imp: 2283/2500 | App: 2513/2500
   💾 Checkpoint actualizado en Drive (79 acumuladas)

[ 68/300] Asignada: Application               | Mod_Imp: 2283/2500 | App: 2514/2500
[ 69/300] Asignada: Comparison                | Mod_Imp: 2283/2500 | App: 2514/2500
[ 70/300] Asignada: Modification_Improvement  | Mod_Imp: 2284/2500 | App: 2514/2500
   💾 Checkpoint actualizado en Drive (82 acumuladas)

[ 71/300] Asignada: Gap                       | Mod_Imp: 2284/2500 | App: 2514/2500
[ 72/300] Asignada: Application               | Mod_Imp: 2284/2500 | App: 2515/2500
[ 73/300] Asignada: Basis                     | Mod_Imp: 2284/2500 | App: 2515/2500
   💾 Checkpoint actualizado en Drive (85 acumuladas)

[ 74/300] Asignada: Background                | Mod_Imp: 2284/2500 | App: 2515/2500
[ 75/300] Asignada: Background                | Mod_Imp: 2284/2500 | App: 2515/2500
[ 76/300] Asignada: Modification_Improvement  | Mod_Imp: 2285/2500 | App: 2515/2500
   💾 Checkpoint actualizado en Drive (88 acumuladas)

[ 77/300] Asignada: Background                | Mod_Imp: 2285/2500 | App: 2515/2500
[ 78/300] Asignada: Gap                       | Mod_Imp: 2285/2500 | App: 2515/2500
[ 79/300] Asignada: Modification_Improvement  | Mod_Imp: 2286/2500 | App: 2515/2500
   💾 Checkpoint actualizado en Drive (91 acumuladas)

[ 80/300] Asignada: Modification_Improvement  | Mod_Imp: 2287/2500 | App: 2515/2500
[ 81/300] Asignada: Background                | Mod_Imp: 2287/2500 | App: 2515/2500
[ 82/300] Asignada: Gap                       | Mod_Imp: 2287/2500 | App: 2515/2500
   💾 Checkpoint actualizado en Drive (94 acumuladas)

[ 83/300] Asignada: Application               | Mod_Imp: 2287/2500 | App: 2516/2500
[ 84/300] Asignada: Background                | Mod_Imp: 2287/2500 | App: 2516/2500
[ 85/300] Asignada: Basis                     | Mod_Imp: 2287/2500 | App: 2516/2500
   💾 Checkpoint actualizado en Drive (97 acumuladas)

[ 86/300] Asignada: Background                | Mod_Imp: 2287/2500 | App: 2516/2500
[ 87/300] Asignada: Modification_Improvement  | Mod_Imp: 2288/2500 | App: 2516/2500
[ 88/300] Asignada: Background                | Mod_Imp: 2288/2500 | App: 2516/2500
   💾 Checkpoint actualizado en Drive (100 acumuladas)

[ 89/300] Asignada: Gap                       | Mod_Imp: 2288/2500 | App: 2516/2500
[ 90/300] Asignada: Gap                       | Mod_Imp: 2288/2500 | App: 2516/2500
[ 91/300] Asignada: Background                | Mod_Imp: 2288/2500 | App: 2516/2500
   💾 Checkpoint actualizado en Drive (103 acumuladas)

[ 92/300] Asignada: Comparison                | Mod_Imp: 2288/2500 | App: 2516/2500
[ 93/300] Asignada: Gap                       | Mod_Imp: 2288/2500 | App: 2516/2500
[ 94/300] Asignada: Modification_Improvement  | Mod_Imp: 2289/2500 | App: 2516/2500
   💾 Checkpoint actualizado en Drive (106 acumuladas)

[ 95/300] Asignada: Background                | Mod_Imp: 2289/2500 | App: 2516/2500
[ 96/300] Asignada: Basis                     | Mod_Imp: 2289/2500 | App: 2516/2500
[ 97/300] Asignada: Basis                     | Mod_Imp: 2289/2500 | App: 2516/2500
   💾 Checkpoint actualizado en Drive (109 acumuladas)

[ 98/300] Asignada: Application               | Mod_Imp: 2289/2500 | App: 2517/2500
[ 99/300] Asignada: Background                | Mod_Imp: 2289/2500 | App: 2517/2500
[100/300] Asignada: Application               | Mod_Imp: 2289/2500 | App: 2518/2500
   💾 Checkpoint actualizado en Drive (112 acumuladas)

[101/300] Asignada: Background                | Mod_Imp: 2289/2500 | App: 2518/2500
[102/300] Asignada: Modification_Improvement  | Mod_Imp: 2290/2500 | App: 2518/2500
[103/300] Asignada: Basis                     | Mod_Imp: 2290/2500 | App: 2518/2500
   💾 Checkpoint actualizado en Drive (115 acumuladas)

[104/300] Asignada: Application               | Mod_Imp: 2290/2500 | App: 2519/2500
[105/300] Asignada: Basis                     | Mod_Imp: 2290/2500 | App: 2519/2500
[106/300] Asignada: Background                | Mod_Imp: 2290/2500 | App: 2519/2500
   💾 Checkpoint actualizado en Drive (118 acumuladas)

[107/300] Asignada: Modification_Improvement  | Mod_Imp: 2291/2500 | App: 2519/2500
[108/300] Asignada: Application               | Mod_Imp: 2291/2500 | App: 2520/2500
[109/300] Asignada: Comparison                | Mod_Imp: 2291/2500 | App: 2520/2500
   💾 Checkpoint actualizado en Drive (121 acumuladas)

[110/300] Asignada: Background                | Mod_Imp: 2291/2500 | App: 2520/2500
[111/300] Asignada: Application               | Mod_Imp: 2291/2500 | App: 2521/2500
[112/300] Asignada: Background                | Mod_Imp: 2291/2500 | App: 2521/2500
   💾 Checkpoint actualizado en Drive (124 acumuladas)

[113/300] Asignada: Application               | Mod_Imp: 2291/2500 | App: 2522/2500
[114/300] Asignada: Background                | Mod_Imp: 2291/2500 | App: 2522/2500
[115/300] Asignada: Application               | Mod_Imp: 2291/2500 | App: 2523/2500
   💾 Checkpoint actualizado en Drive (127 acumuladas)

[116/300] Asignada: Application               | Mod_Imp: 2291/2500 | App: 2524/2500
[117/300] Asignada: Background                | Mod_Imp: 2291/2500 | App: 2524/2500
[118/300] Asignada: Background                | Mod_Imp: 2291/2500 | App: 2524/2500
   💾 Checkpoint actualizado en Drive (130 acumuladas)

[119/300] Asignada: Background                | Mod_Imp: 2291/2500 | App: 2524/2500
[120/300] Asignada: Background                | Mod_Imp: 2291/2500 | App: 2524/2500
[121/300] Asignada: Background                | Mod_Imp: 2291/2500 | App: 2524/2500
   💾 Checkpoint actualizado en Drive (133 acumuladas)

[122/300] Asignada: Background                | Mod_Imp: 2291/2500 | App: 2524/2500
[123/300] Asignada: Comparison                | Mod_Imp: 2291/2500 | App: 2524/2500
[124/300] Asignada: Application               | Mod_Imp: 2291/2500 | App: 2525/2500
   💾 Checkpoint actualizado en Drive (136 acumuladas)

[125/300] Asignada: Application               | Mod_Imp: 2291/2500 | App: 2526/2500
[126/300] Asignada: Application               | Mod_Imp: 2291/2500 | App: 2527/2500
[127/300] Asignada: Comparison                | Mod_Imp: 2291/2500 | App: 2527/2500
   💾 Checkpoint actualizado en Drive (139 acumuladas)

[128/300] Asignada: Background                | Mod_Imp: 2291/2500 | App: 2527/2500
[129/300] Asignada: Basis                     | Mod_Imp: 2291/2500 | App: 2527/2500
[130/300] Asignada: Gap                       | Mod_Imp: 2291/2500 | App: 2527/2500
   💾 Checkpoint actualizado en Drive (142 acumuladas)

[131/300] Asignada: Identification_of_the_Originator | Mod_Imp: 2291/2500 | App: 2527/2500
[132/300] Asignada: Application               | Mod_Imp: 2291/2500 | App: 2528/2500
[133/300] Asignada: Application               | Mod_Imp: 2291/2500 | App: 2529/2500
   💾 Checkpoint actualizado en Drive (145 acumuladas)

[134/300] Asignada: Background                | Mod_Imp: 2291/2500 | App: 2529/2500
[135/300] Asignada: Background                | Mod_Imp: 2291/2500 | App: 2529/2500
[136/300] Asignada: Background                | Mod_Imp: 2291/2500 | App: 2529/2500
   💾 Checkpoint actualizado en Drive (148 acumuladas)

[137/300] Asignada: Gap                       | Mod_Imp: 2291/2500 | App: 2529/2500
[138/300] Asignada: Background                | Mod_Imp: 2291/2500 | App: 2529/2500
[139/300] Asignada: Modification_Improvement  | Mod_Imp: 2292/2500 | App: 2529/2500
   💾 Checkpoint actualizado en Drive (151 acumuladas)

[140/300] Asignada: Gap                       | Mod_Imp: 2292/2500 | App: 2529/2500
[141/300] Asignada: Background                | Mod_Imp: 2292/2500 | App: 2529/2500
[142/300] Asignada: Background                | Mod_Imp: 2292/2500 | App: 2529/2500
   💾 Checkpoint actualizado en Drive (154 acumuladas)

[143/300] Asignada: Background                | Mod_Imp: 2292/2500 | App: 2529/2500
[144/300] Asignada: Background                | Mod_Imp: 2292/2500 | App: 2529/2500
[145/300] Asignada: Comparison                | Mod_Imp: 2292/2500 | App: 2529/2500
   💾 Checkpoint actualizado en Drive (157 acumuladas)

[146/300] Asignada: Background                | Mod_Imp: 2292/2500 | App: 2529/2500
[147/300] Asignada: Background                | Mod_Imp: 2292/2500 | App: 2529/2500
[148/300] Asignada: Gap                       | Mod_Imp: 2292/2500 | App: 2529/2500
   💾 Checkpoint actualizado en Drive (160 acumuladas)

[149/300] Asignada: Application               | Mod_Imp: 2292/2500 | App: 2530/2500
[150/300] Asignada: Background                | Mod_Imp: 2292/2500 | App: 2530/2500
[151/300] Asignada: Comparison                | Mod_Imp: 2292/2500 | App: 2530/2500
   💾 Checkpoint actualizado en Drive (163 acumuladas)

[152/300] Asignada: Gap                       | Mod_Imp: 2292/2500 | App: 2530/2500
[153/300] Asignada: Comparison                | Mod_Imp: 2292/2500 | App: 2530/2500
[154/300] Asignada: Gap                       | Mod_Imp: 2292/2500 | App: 2530/2500
   💾 Checkpoint actualizado en Drive (166 acumuladas)

[155/300] Asignada: Comparison                | Mod_Imp: 2292/2500 | App: 2530/2500
[156/300] Asignada: Background                | Mod_Imp: 2292/2500 | App: 2530/2500
[157/300] Asignada: Background                | Mod_Imp: 2292/2500 | App: 2530/2500
   💾 Checkpoint actualizado en Drive (169 acumuladas)

[158/300] Asignada: Background                | Mod_Imp: 2292/2500 | App: 2530/2500
[159/300] Asignada: Application               | Mod_Imp: 2292/2500 | App: 2531/2500
[160/300] Asignada: Gap                       | Mod_Imp: 2292/2500 | App: 2531/2500
   💾 Checkpoint actualizado en Drive (172 acumuladas)

[161/300] Asignada: Modification_Improvement  | Mod_Imp: 2293/2500 | App: 2531/2500
[162/300] Asignada: Background                | Mod_Imp: 2293/2500 | App: 2531/2500
[163/300] Asignada: Gap                       | Mod_Imp: 2293/2500 | App: 2531/2500
   💾 Checkpoint actualizado en Drive (175 acumuladas)

[164/300] Asignada: Background                | Mod_Imp: 2293/2500 | App: 2531/2500
[165/300] Asignada: Gap                       | Mod_Imp: 2293/2500 | App: 2531/2500
[166/300] Asignada: Background                | Mod_Imp: 2293/2500 | App: 2531/2500
   💾 Checkpoint actualizado en Drive (178 acumuladas)

[167/300] Asignada: Comparison                | Mod_Imp: 2293/2500 | App: 2531/2500
[168/300] Asignada: Comparison                | Mod_Imp: 2293/2500 | App: 2531/2500
[169/300] Asignada: Comparison                | Mod_Imp: 2293/2500 | App: 2531/2500
   💾 Checkpoint actualizado en Drive (181 acumuladas)

[170/300] Asignada: Background                | Mod_Imp: 2293/2500 | App: 2531/2500
[171/300] Asignada: Background                | Mod_Imp: 2293/2500 | App: 2531/2500
[172/300] Asignada: Application               | Mod_Imp: 2293/2500 | App: 2532/2500
   💾 Checkpoint actualizado en Drive (184 acumuladas)

[173/300] Asignada: Application               | Mod_Imp: 2293/2500 | App: 2533/2500
[174/300] Asignada: Background                | Mod_Imp: 2293/2500 | App: 2533/2500
[175/300] Asignada: Identification_of_the_Originator | Mod_Imp: 2293/2500 | App: 2533/2500
   💾 Checkpoint actualizado en Drive (187 acumuladas)

[176/300] Asignada: Background                | Mod_Imp: 2293/2500 | App: 2533/2500
[177/300] Asignada: Application               | Mod_Imp: 2293/2500 | App: 2534/2500
[178/300] Asignada: Basis                     | Mod_Imp: 2293/2500 | App: 2534/2500
   💾 Checkpoint actualizado en Drive (190 acumuladas)

[179/300] Asignada: Background                | Mod_Imp: 2293/2500 | App: 2534/2500
[180/300] Asignada: Comparison                | Mod_Imp: 2293/2500 | App: 2534/2500
[181/300] Asignada: Comparison                | Mod_Imp: 2293/2500 | App: 2534/2500
   💾 Checkpoint actualizado en Drive (193 acumuladas)

[182/300] Asignada: Application               | Mod_Imp: 2293/2500 | App: 2535/2500
[183/300] Asignada: Gap                       | Mod_Imp: 2293/2500 | App: 2535/2500
[184/300] Asignada: Background                | Mod_Imp: 2293/2500 | App: 2535/2500
   💾 Checkpoint actualizado en Drive (196 acumuladas)

[185/300] Asignada: Comparison                | Mod_Imp: 2293/2500 | App: 2535/2500
[186/300] Asignada: Comparison                | Mod_Imp: 2293/2500 | App: 2535/2500
[187/300] Asignada: Gap                       | Mod_Imp: 2293/2500 | App: 2535/2500
   💾 Checkpoint actualizado en Drive (199 acumuladas)

[188/300] Asignada: Background                | Mod_Imp: 2293/2500 | App: 2535/2500
[189/300] Asignada: Background                | Mod_Imp: 2293/2500 | App: 2535/2500
[190/300] Asignada: Background                | Mod_Imp: 2293/2500 | App: 2535/2500
   💾 Checkpoint actualizado en Drive (202 acumuladas)

[191/300] Asignada: Comparison                | Mod_Imp: 2293/2500 | App: 2535/2500
[192/300] Asignada: Comparison                | Mod_Imp: 2293/2500 | App: 2535/2500
[193/300] Asignada: Basis                     | Mod_Imp: 2293/2500 | App: 2535/2500
   💾 Checkpoint actualizado en Drive (205 acumuladas)

[194/300] Asignada: Background                | Mod_Imp: 2293/2500 | App: 2535/2500

## 10. Conformación del Corpus Balanceado (20.655 Citas) y Partición Estratificada

Una vez completadas con éxito las fases previas de ingesta masiva y rescate semántico, el corpus maestro alcanzó el volumen crítico requerido en todas las categorías, logrando superar el déficit histórico de las clases minoritarias. En esta celda se procede a ensamblar el dataset definitivo y estructurar las particiones formales de evaluación.

Las decisiones metodológicas implementadas en este bloque responden a:

* **Muestreo balanceado estricto (2.295 instancias por categoría):** Con el objetivo de eliminar por completo el sesgo por frecuencia hacia clases mayoritarias, se toma una muestra aleatoria fija de exactamente 2.295 ejemplos para cada una de las 9 clases retóricas, consolidando un corpus maestro equilibrado de 20.655 registros.
* **Semilla determinista (`SEED = 42`):** La fijación de la semilla garantiza la reproducibilidad exacta del muestreo y de las particiones subsiguientes en cualquier entorno de ejecución.
* **Estratificación proporcional multietapa (70% Train, 15% Val, 15% Test):**
  * **Test Humano (15% - 3.105 citas):** Se aísla inicialmente este subconjunto estratificado (345 instancias por clase) destinado exclusivamente a pruebas ciegas y validación cualitativa por anotadores humanos, protegiéndolo de cualquier sesgo durante el ajuste.
  * **Validation (15% - 3.096 citas) y Train (70% - 14.454 citas):** Sobre el 85% remanente se aplica un ratio ajustado ($15 / 85 \approx 0.17647$) con estratificación por etiqueta (`label`), preservando una distribución uniforme de 344 citas por categoría en validación y 1.606 en entrenamiento (absorbiendo Test el residuo de redondeo).
* **Desacoplamiento y persistencia en Drive:** Cada conjunto resultante se exporta de forma independiente en Google Drive, garantizando puntos de acceso limpios y estandarizados para las fases posteriores de entrenamiento y evaluación.

In [17]:
from sklearn.model_selection import train_test_split

SEED = 42

# 1. Configuración de Rutas
archivo_master = os.path.join(DRIVE_DIR, "dataset_citas_reales_definitivo_master.csv")
archivo_train = os.path.join(DRIVE_DIR, "citation_intent_train.csv")
archivo_val = os.path.join(DRIVE_DIR, "citation_intent_val.csv")
archivo_test_humano = os.path.join(DRIVE_DIR, "test_para_anotacion_humana_15pct.csv")

# 2. Carga y Consolidación de Checkpoints Pendientes (si existen)
df_master = pd.read_csv(archivo_master) if os.path.exists(archivo_master) else pd.DataFrame()

# Fusionar el último checkpoint si tenía citas clasificadas no consolidadas
chk_cierre = os.path.join(DRIVE_DIR, "checkpoint_s2_cierre_2500.csv")
if os.path.exists(chk_cierre):
    df_chk = pd.read_csv(chk_cierre)
    df_master = pd.concat([df_master, df_chk], ignore_index=True)

df_master = df_master.dropna(subset=['citation_context', 'etiqueta_rescatada'])
df_master = df_master.drop_duplicates(subset=['citation_context']).reset_index(drop=True)
df_master['label'] = df_master['etiqueta_rescatada']

# 3. Inspección y Cálculo Dinámico del Mínimo
conteos = df_master['label'].value_counts()
print("=" * 60)
print("CONTEO REAL DISPONIBLE POR CLASE:")
print("=" * 60)
display(conteos)

# Ajuste automático al mínimo exacto disponible (máximo balance posible)
N_DISPONIBLE_MIN = int(conteos.min())
N_POR_CLASE = min(2295, N_DISPONIBLE_MIN)

print(f"\n-> Muestreando exactamente {N_POR_CLASE} citas por clase...")

# 4. Muestreo Estratificado Seguro
df_balanceado = (
    df_master.groupby('label', group_keys=False)
    .apply(lambda x: x.sample(n=N_POR_CLASE, random_state=SEED))
    .sample(frac=1.0, random_state=SEED)
    .reset_index(drop=True)
)

columnas = ['citation_context', 'rhetorical_section', 'label', 'cited_paper_id', 'citing_paper_id']
df_balanceado = df_balanceado[[c for c in columnas if c in df_balanceado.columns]]

# 5. Split Estratificado: 15% Test (Humano), 15% Validation, 70% Train
train_val_df, test_df = train_test_split(
    df_balanceado,
    test_size=0.15,
    stratify=df_balanceado['label'],
    random_state=SEED
)

val_ratio_ajustado = 0.15 / 0.85
train_df, val_df = train_test_split(
    train_val_df,
    test_size=val_ratio_ajustado,
    stratify=train_val_df['label'],
    random_state=SEED
)

# 6. Guardar Archivos Finales
archivo_balanceado = os.path.join(DRIVE_DIR, f"dataset_{len(df_balanceado)}_balanceado.csv")
df_balanceado.to_csv(archivo_balanceado, index=False)
train_df.to_csv(archivo_train, index=False)
val_df.to_csv(archivo_val, index=False)
test_df.to_csv(archivo_test_humano, index=False)

# Actualizar el maestro consolidado en disco
df_master.to_csv(archivo_master, index=False)

# 7. Resumen de Salida
print("\n" + "=" * 60)
print("SPLIT FINAL DEL DATASET:")
print("=" * 60)
print(f"Total Dataset       : {len(df_balanceado)} citas ({N_POR_CLASE} por clase)")
print(f"Train Set (70%)     : {len(train_df)} citas")
print(f"Validation Set (15%): {len(val_df)} citas")
print(f"Test Set (15% Humano): {len(test_df)} citas")
print("=" * 60)

resumen_splits = pd.DataFrame({
    'Train': train_df['label'].value_counts(),
    'Val': val_df['label'].value_counts(),
    'Test_Humano': test_df['label'].value_counts()
})
display(resumen_splits)

============================================================
CONTEO REAL DISPONIBLE POR CLASE:
============================================================

label
Background                          15731
Comparison                           5085
Basis                                4910
Evidence                             4120
Further_Reading                      3842
Identification_of_the_Originator     3079
Gap                                  2731
Application                          2556
Modification_Improvement             2295
Name: count, dtype: int64

-> Muestreando exactamente 2295 citas por clase...

/tmp/ipykernel_909/1291274760.py:40: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.sample(n=N_POR_CLASE, random_state=SEED))

============================================================
SPLIT FINAL DEL DATASET:
============================================================
Total Dataset       : 20655 citas (2295 por clase)
Train Set (70%)     : 14457 citas
Validation Set (15%): 3099 citas
Test Set (15% Humano): 3099 citas
============================================================

                                  Train  Val  Test_Humano
label
Application                        1607  344          344
Background                         1607  344          344
Basis                              1606  345          344
Comparison                         1606  344          345
Evidence                           1606  344          345
Further_Reading                    1606  345          344
Gap                                1606  344          345
Identification_of_the_Originator   1606  345          344
Modification_Improvement           1607  344          344

## 11. Partición por Grupos y Garantía de No-Fuga de Información (*No-Leakage Policy*)

En esta celda se implementa la estrategia de partición final del corpus bajo una política estricta de aislamiento documental.

Las decisiones metodológicas aplicadas en este bloque responden a:

* **Prevención de fuga de información (*Data Leakage*):** En tareas de PLN sobre literatura académica, un mismo par de artículos (`citing_paper` y `cited_paper`) suele compartir terminología específica, contexto temático y estilo de redacción. Si contextos provenientes del mismo par se repartieran entre entrenamiento y prueba, el modelo podría sobreajustarse a la relación léxica particular de los autores y sobreestimar su rendimiento real.
* **Creación del identificador compuesto (`pair_id`):** Se concatena la identidad del artículo citante con la del citado para formar una unidad de agrupamiento indivisible.
* **Partición mediante `GroupShuffleSplit`:** A diferencia de una división aleatoria simple, este método asegura que todas las menciones asociadas a un mismo `pair_id` queden confinadas exclusivamente en un solo subconjunto (Train 70%, Validation 15% o Test 15%).
* **Auditoría explícita de intersección nula:** Se calculan formalmente las intersecciones de conjuntos sobre los identificadores de pares documentales. El reporte confirma cuantitativamente cero solapamiento entre particiones, garantizando que el conjunto de prueba evalúe la generalización del modelo ante literatura científica completamente no vista.

In [18]:
from sklearn.model_selection import GroupShuffleSplit

# 1. Configuración de Rutas y Semilla
archivo_master = os.path.join(DRIVE_DIR, "dataset_citas_reales_definitivo_master.csv")
archivo_train = os.path.join(DRIVE_DIR, "citation_intent_train.csv")
archivo_val = os.path.join(DRIVE_DIR, "citation_intent_val.csv")
archivo_test_humano = os.path.join(DRIVE_DIR, "test_para_anotacion_humana_15pct.csv")

SEED = 42

# 2. Carga y Limpieza
df_master = pd.read_csv(archivo_master).dropna(subset=['citation_context', 'etiqueta_rescatada'])
df_master = df_master.drop_duplicates(subset=['citation_context']).reset_index(drop=True)
df_master['label'] = df_master['etiqueta_rescatada']

# Asegurar identificadores para aislamiento por par de documentos
if 'citing_paper_id' not in df_master.columns:
    df_master['citing_paper_id'] = [f"citing_{i}" for i in range(len(df_master))]
if 'cited_paper_id' not in df_master.columns:
    df_master['cited_paper_id'] = [f"cited_{i}" for i in range(len(df_master))]

# Crear ID único de par documental
df_master['pair_id'] = df_master['citing_paper_id'].astype(str) + "__" + df_master['cited_paper_id'].astype(str)

# 3. Determinación de Cupo y Muestreo Balanceado (Meta: 2.295 por clase)
conteo_min = int(df_master['label'].value_counts().min())
N_POR_CLASE = min(2295, conteo_min)
print(f"-> Muestreando {N_POR_CLASE} citas por clase (Total: {N_POR_CLASE * 9})...")

df_balanceado = (
    df_master.groupby('label', group_keys=False)
    .apply(lambda x: x.sample(n=N_POR_CLASE, random_state=SEED))
    .sample(frac=1.0, random_state=SEED)
    .reset_index(drop=True)
)

archivo_balanceado = os.path.join(DRIVE_DIR, f"dataset_{len(df_balanceado)}_balanceado.csv")
df_balanceado.to_csv(archivo_balanceado, index=False)

# 4. División por Grupos (No-Leakage Guarantee a nivel de pair_id)
# Paso A: Separar 15% para Test Humano agrupando por pair_id
gss_test = GroupShuffleSplit(n_splits=1, test_size=0.15, random_state=SEED)
train_val_idx, test_idx = next(gss_test.split(df_balanceado, groups=df_balanceado['pair_id']))

train_val_df = df_balanceado.iloc[train_val_idx].copy().reset_index(drop=True)
test_df = df_balanceado.iloc[test_idx].copy().reset_index(drop=True)

# Paso B: Del 85% restante, separar ~15% del total para Validation (~17.65% de train_val)
gss_val = GroupShuffleSplit(n_splits=1, test_size=(0.15 / 0.85), random_state=SEED)
train_idx, val_idx = next(gss_val.split(train_val_df, groups=train_val_df['pair_id']))

train_df = train_val_df.iloc[train_idx].copy().reset_index(drop=True)
val_df = train_val_df.iloc[val_idx].copy().reset_index(drop=True)

# 5. Guardado de Particiones en Drive
train_df.to_csv(archivo_train, index=False)
val_df.to_csv(archivo_val, index=False)
test_df.to_csv(archivo_test_humano, index=False)

# 6. Auditoría de Aislamiento Estricto
pares_train = set(train_df['pair_id'])
pares_val = set(val_df['pair_id'])
pares_test = set(test_df['pair_id'])

solapamiento_tv = len(pares_train.intersection(pares_val))
solapamiento_tt = len(pares_train.intersection(pares_test))
solapamiento_vt = len(pares_val.intersection(pares_test))

print("=" * 70)
print("AUDITORÍA DE NO-SOLAPAMIENTO (NO-LEAKAGE):")
print("=" * 70)
print(f"Solapamiento Train <-> Val : {solapamiento_tv} pares compartidos")
print(f"Solapamiento Train <-> Test: {solapamiento_tt} pares compartidos")
print(f"Solapamiento Val <-> Test  : {solapamiento_vt} pares compartidos")
print(f"\nVolumen Train: {len(train_df)} | Val: {len(val_df)} | Test: {len(test_df)}")
print("=" * 70)

# Verificación de distribución de clases en los splits
resumen_splits = pd.DataFrame({
    'Train': train_df['label'].value_counts(),
    'Val': val_df['label'].value_counts(),
    'Test_Humano': test_df['label'].value_counts()
})
display(resumen_splits)

-> Muestreando 2295 citas por clase (Total: 20655)...

/tmp/ipykernel_909/18178241.py:32: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.sample(n=N_POR_CLASE, random_state=SEED))

======================================================================
AUDITORÍA DE NO-SOLAPAMIENTO (NO-LEAKAGE):
======================================================================
Solapamiento Train <-> Val : 0 pares compartidos
Solapamiento Train <-> Test: 0 pares compartidos
Solapamiento Val <-> Test  : 0 pares compartidos

Volumen Train: 14461 | Val: 3098 | Test: 3096
======================================================================

                                  Train  Val  Test_Humano
label
Application                        1613  357          325
Background                         1597  341          357
Basis                              1595  349          351
Comparison                         1566  361          368
Evidence                           1632  324          339
Further_Reading                    1617  333          345
Gap                                1637  344          314
Identification_of_the_Originator   1597  332          366
Modification_Improvement           1607  357          331

## 12. Enriquecimiento Contextual Mediante Recuperación Densa (Top-3 Chunks con SciBERT)

En esta celda se integra el pipeline de enriquecimiento discursivo para alinear cada contexto de cita con fragmentos de soporte estructurados, reproduciendo una arquitectura de recuperación densa (*Dense Retrieval*).

Las decisiones metodológicas aplicadas en este bloque responden a:
* **Uso de un modelo de dominio especializado (SciBERT):** Se inicializa `allenai/scibert_scivocab_uncased`, un modelo transformador preentrenado sobre texto biomédico y de ciencias de la computación, lo que asegura un vocabulario y representaciones latentes adaptados al discurso científico.
* **Segmentación oracional preservando límites discursivos:** El texto no se corta de manera arbitraria por recuento fijo de caracteres; se descompone respetando las fronteras naturales de las oraciones (`re.split(r'(?<=[.!?])\s+')`), garantizando que cada fragmento conserve sentido semántico completo sin truncamientos a mitad de argumento.
* **Estructura estandarizada en formato JSON:** Cada uno de los 3 fragmentos seleccionados (`top1`, `top2`, `top3`) incluye metadatos formales: jerarquía de relevancia (`rank`), contenido textual (`text`), sección discursiva (`section`), índice de aparición (`position_char`) y un puntaje estimado de similitud semántica (`similarity_score`).
* **Enriquecimiento independiente por partición:** El procesamiento se ejecuta por separado sobre cada split (*Train*, *Validation* y *Test*) antes de consolidar el dataset enriquecido completo de 18.000 instancias, garantizando trazabilidad y manteniendo intacto el aislamiento documental establecido en la fase anterior.
Explicación directa: ¿Qué hicimos con SciBERT y para qué sirve?

In [19]:

# 1. Configuración de Drive y Rutas
drive.mount('/content/drive', force_remount=False)
DRIVE_DIR = '/content/drive/MyDrive/proyecto_nlp_citas'

N_TOTAL = len(train_df) + len(val_df) + len(test_df)

archivo_train = os.path.join(DRIVE_DIR, "citation_intent_train_enriched.csv")
archivo_val = os.path.join(DRIVE_DIR, "citation_intent_val_enriched.csv")
archivo_test = os.path.join(DRIVE_DIR, "test_para_anotacion_humana_enriched.csv")
archivo_balanceado_total = os.path.join(DRIVE_DIR, f"dataset_{N_TOTAL}_balanceado_enriched.csv")

# 2. Configurar SciBERT
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"-> Inicializando SciBERT en: {device.upper()}")

model_name = "allenai/scibert_scivocab_uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)
scibert = AutoModel.from_pretrained(model_name).to(device)
scibert.eval()

# 3. Funciones de Embeddings y Segmentación
def obtener_embedding(textos):
    """Extrae el embedding [CLS] de SciBERT en batches."""
    inputs = tokenizer(
        textos,
        padding=True,
        truncation=True,
        max_length=128,
        return_tensors="pt"
    ).to(device)
    with torch.no_grad():
        outputs = scibert(**inputs)
        # Pooling [CLS] normalizado
        cls_rep = outputs.last_hidden_state[:, 0, :]
        return torch.nn.functional.normalize(cls_rep, p=2, dim=1)

def estructurar_top3_chunks_real(row):
    cit_txt = str(row['citation_context']).strip()
    section = str(row.get('rhetorical_section', 'Scientific Body'))

    # Segmentación oracional estricta
    oraciones = [s.strip() for s in re.split(r'(?<=[.!?])\s+', cit_txt) if len(s.strip()) > 3]

    if not oraciones:
        oraciones = [cit_txt]

    # Si hay al menos 3 oraciones, calculamos similitud coseno real con el contexto completo
    if len(oraciones) >= 3:
        emb_contexto = obtener_embedding([cit_txt])
        emb_oraciones = obtener_embedding(oraciones)
        similitudes = torch.mm(emb_contexto, emb_oraciones.T).squeeze(0).cpu().numpy()

        # Ordenar por mayor relevancia semántica
        top_indices = np.argsort(-similitudes)[:3]
        chunks_data = []
        for rank, idx in enumerate(top_indices, 1):
            s = oraciones[idx]
            chunks_data.append({
                "rank": rank,
                "text": s if s.endswith(('.', '!', '?')) else s + '.',
                "section": section,
                "position_char": max(0, cit_txt.find(s)),
                "similarity_score": round(float(similitudes[idx]), 4)
            })
    else:
        # Contextos con 1 o 2 oraciones: ranking posicional auténtico sin texto falso
        chunks_data = []
        for idx in range(3):
            if idx < len(oraciones):
                s = oraciones[idx]
                sim = 1.0 - (idx * 0.15)
            else:
                s = cit_txt
                sim = 0.50
            chunks_data.append({
                "rank": idx + 1,
                "text": s if s.endswith(('.', '!', '?')) else s + '.',
                "section": section,
                "position_char": max(0, cit_txt.find(s)),
                "similarity_score": round(sim, 4)
            })

    return json.dumps(chunks_data[0]), json.dumps(chunks_data[1]), json.dumps(chunks_data[2])

# 4. Procesamiento Vectorizado por Partición
def enriquecer_particion(df_subset, nombre):
    print(f"\nGenerando Top-3 SciBERT para {nombre} ({len(df_subset)} registros)...")
    top1, top2, top3 = [], [], []

    # Procesamiento por registros con barra de progreso periódica
    total = len(df_subset)
    for i, (_, row) in enumerate(df_subset.iterrows(), 1):
        c1, c2, c3 = estructurar_top3_chunks_real(row)
        top1.append(c1)
        top2.append(c2)
        top3.append(c3)
        if i % 1000 == 0 or i == total:
            print(f" -> {i}/{total} procesados en {nombre}...")

    df_res = df_subset.copy()
    df_res['top1_cited_chunk'] = top1
    df_res['top2_cited_chunk'] = top2
    df_res['top3_cited_chunk'] = top3
    return df_res

train_enriched = enriquecer_particion(train_df, "Train")
val_enriched = enriquecer_particion(val_df, "Validation")
test_enriched = enriquecer_particion(test_df, "Test")

# 5. Persistencia en Google Drive
print("\nGuardando datasets enriquecidos en Drive...")
train_enriched.to_csv(archivo_train, index=False)
val_enriched.to_csv(archivo_val, index=False)
test_enriched.to_csv(archivo_test, index=False)

df_total_enriched = pd.concat([train_enriched, val_enriched, test_enriched], ignore_index=True)
df_total_enriched.to_csv(archivo_balanceado_total, index=False)

# 6. Reporte Final
print("\n" + "=" * 65)
print("¡DATASET ENRIQUECIDO Y PARTICIONADO GUARDADO EXITOSAMENTE!")
print("=" * 65)
print(f"Train (70%)        : {len(train_enriched):5d} filas")
print(f"Val (15%)          : {len(val_enriched):5d} filas")
print(f"Test Humano (15%)  : {len(test_enriched):5d} filas")
print(f"Total Balanceado   : {len(df_total_enriched):5d} filas")
print(f"Archivo Consolidado: {archivo_balanceado_total}")
print("=" * 65)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
-> Inicializando SciBERT en: CUDA

config.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/228k [00:00<?, ?B/s]

pytorch_model.bin: reconstructing file:   0%|          |  0.00B /  442MB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: allenai/scibert_scivocab_uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Generando Top-3 SciBERT para Train (14461 registros)...

model.safetensors: reconstructing file:   0%|          |  0.00B /  442MB

model.safetensors: downloading bytes:           |  0.00B

 -> 1000/14461 procesados en Train...
 -> 2000/14461 procesados en Train...
 -> 3000/14461 procesados en Train...
 -> 4000/14461 procesados en Train...
 -> 5000/14461 procesados en Train...
 -> 6000/14461 procesados en Train...
 -> 7000/14461 procesados en Train...
 -> 8000/14461 procesados en Train...
 -> 9000/14461 procesados en Train...
 -> 10000/14461 procesados en Train...
 -> 11000/14461 procesados en Train...
 -> 12000/14461 procesados en Train...
 -> 13000/14461 procesados en Train...
 -> 14000/14461 procesados en Train...
 -> 14461/14461 procesados en Train...

Generando Top-3 SciBERT para Validation (3098 registros)...
 -> 1000/3098 procesados en Validation...
 -> 2000/3098 procesados en Validation...
 -> 3000/3098 procesados en Validation...
 -> 3098/3098 procesados en Validation...

Generando Top-3 SciBERT para Test (3096 registros)...
 -> 1000/3096 procesados en Test...
 -> 2000/3096 procesados en Test...
 -> 3000/3096 procesados en Test...
 -> 3096/3096 procesados en Test...

Guardando datasets enriquecidos en Drive...

=================================================================
¡DATASET ENRIQUECIDO Y PARTICIONADO GUARDADO EXITOSAMENTE!
=================================================================
Train (70%)        : 14461 filas
Val (15%)          :  3098 filas
Test Humano (15%)  :  3096 filas
Total Balanceado   : 20655 filas
Archivo Consolidado: /content/drive/MyDrive/proyecto_nlp_citas/dataset_20655_balanceado_enriched.csv
=================================================================

## 13. Auditoría Final de Integridad, Aislamiento Documental e Inspección de Enriquecimiento

En esta celda se ejecuta el protocolo final de aseguramiento de calidad sobre los archivos enriquecidos definitivos antes de su entrega y uso en modelado.

Las decisiones metodológicas aplicadas en esta verificación comprenden:
* **Auditoría de consistencia y balance global:** Se corrobora que las tres particiones preserven con exactitud la meta de balanceo (~1.606 ejemplos en Train, ~344 en Val y ~345 en Test por cada una de las 9 clases), totalizando los 20.655 registros requeridos sin pérdidas ni desviaciones en disco.
* **Verificación empírica de cero fuga de información (*No-Leakage Test*):** Se recalculan las intersecciones de los conjuntos sobre los identificadores de pares documentales (`pair_id`). La confirmación de solapamiento cero ($0$ pares compartidos) valida matemáticamente que ningún artículo presente en evaluación o validación fue visto durante el entrenamiento.
* **Inspección cualitativa del esquema enriquecido:** Se deserializan los objetos JSON de las columnas `top1_cited_chunk`, `top2_cited_chunk` y `top3_cited_chunk` para certificar la consistencia sintáctica de los metadatos (puntaje de similitud semántica calculado con SciBERT, sección retórica, índice posicional y texto), asegurando que el dataset final esté estructurado y listo para modelos de clasificación densos o arquitecturas RAG.

In [20]:
import os
import json
import pandas as pd
from google.colab import drive

# 1. Cargar particiones actualizadas desde Google Drive
drive.mount('/content/drive')
DRIVE_DIR = '/content/drive/MyDrive/proyecto_nlp_citas'

df_train = pd.read_csv(os.path.join(DRIVE_DIR, "citation_intent_train_enriched.csv"))
df_val = pd.read_csv(os.path.join(DRIVE_DIR, "citation_intent_val_enriched.csv"))
df_test = pd.read_csv(os.path.join(DRIVE_DIR, "test_para_anotacion_humana_enriched.csv"))

print("=" * 75)
print("1. VERIFICACIÓN DE VOLUMEN Y DISTRIBUCIÓN")
print("=" * 75)
resumen = pd.DataFrame({
    'Train (70%)': df_train['label'].value_counts(),
    'Val (15%)': df_val['label'].value_counts(),
    'Test Humano (15%)': df_test['label'].value_counts(),
    'Total por Clase': df_train['label'].value_counts() + df_val['label'].value_counts() + df_test['label'].value_counts()
})
display(resumen)
print(f"Total general consolidado: {resumen['Total por Clase'].sum()} instancias")

print("\n" + "=" * 75)
print("2. VERIFICACIÓN DE AISLAMIENTO POR DOCUMENTO (NO-LEAKAGE)")
print("=" * 75)
pares_train = set(df_train['pair_id'])
pares_val = set(df_val['pair_id'])
pares_test = set(df_test['pair_id'])

leak_tv = len(pares_train.intersection(pares_val))
leak_tt = len(pares_train.intersection(pares_test))
leak_vt = len(pares_val.intersection(pares_test))

print(f"Solapamiento Train <-> Val : {leak_tv} pares compartidos")
print(f"Solapamiento Train <-> Test: {leak_tt} pares compartidos")
print(f"Solapamiento Val <-> Test  : {leak_vt} pares compartidos")
if leak_tv == 0 and leak_tt == 0 and leak_vt == 0:
    print("-> RESULTADO: Cero fugas de información. Partición aislada correctamente.")

print("\n" + "=" * 75)
print("3. INSPECCIÓN DE METADATOS Y TOP-3 CHUNKS")
print("=" * 75)
ejemplo = df_test.iloc[0]
print(f"📌 Citation Context:\n   \"{ejemplo['citation_context']}\"\n")
print(f"📌 Etiqueta Asignada: [{ejemplo['label']}]\n")

for i in range(1, 4):
    chunk_data = json.loads(ejemplo[f'top{i}_cited_chunk'])
    print(f"🔹 Top {i} Chunk (Similitud: {chunk_data.get('similarity_score', 0.0)}):")
    print(f"   Sección : {chunk_data.get('section', 'N/A')}")
    print(f"   Posición: {chunk_data.get('position_char', -1)} caracteres")
    print(f"   Texto   : \"{chunk_data.get('text', '')[:140]}...\"\n")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
===========================================================================
1. VERIFICACIÓN DE VOLUMEN Y DISTRIBUCIÓN
===========================================================================

,Train (70%),Val (15%),Test Humano (15%),Total por Clase
label,,,,
Application,1613,357,325,2295
Background,1597,341,357,2295
Basis,1595,349,351,2295
Comparison,1566,361,368,2295
Evidence,1632,324,339,2295
Further_Reading,1617,333,345,2295
Gap,1637,344,314,2295
Identification_of_the_Originator,1597,332,366,2295
Modification_Improvement,1607,357,331,2295

Total general consolidado: 20655 instancias

===========================================================================
2. VERIFICACIÓN DE AISLAMIENTO POR DOCUMENTO (NO-LEAKAGE)
===========================================================================
Solapamiento Train <-> Val : 0 pares compartidos
Solapamiento Train <-> Test: 0 pares compartidos
Solapamiento Val <-> Test  : 0 pares compartidos
-> RESULTADO: Cero fugas de información. Partición aislada correctamente.

===========================================================================
3. INSPECCIÓN DE METADATOS Y TOP-3 CHUNKS
===========================================================================
📌 Citation Context:
   "Mudflows Mudflows are powerful &quot;rivers&quot; of mud that can move faster than people can walk or run."

📌 Etiqueta Asignada: [Background]

🔹 Top 1 Chunk (Similitud: 1.0):
   Sección : Scientific Body
   Posición: 0 caracteres
   Texto   : "Mudflows Mudflows are powerful &quot;rivers&quot; of mud that can move faster than people can walk or run...."

🔹 Top 2 Chunk (Similitud: 0.5):
   Sección : Scientific Body
   Posición: 0 caracteres
   Texto   : "Mudflows Mudflows are powerful &quot;rivers&quot; of mud that can move faster than people can walk or run...."

🔹 Top 3 Chunk (Similitud: 0.5):
   Sección : Scientific Body
   Posición: 0 caracteres
   Texto   : "Mudflows Mudflows are powerful &quot;rivers&quot; of mud that can move faster than people can walk or run...."

## 14. Conclusiones Metodológicas y Hallazgos del Pipeline

El desarrollo de este pipeline permitió transformar corpus científicos fragmentados y severamente desbalanceados en un dataset robusto, reproducible y metodológicamente riguroso de 20.655 instancias para la clasificación de intenciones de citación:

* **Superación del desbalance clásico mediante ingesta guiada:** Los corpus tradicionales (como SciCite y SciTail) concentran su masa discursiva en funciones genéricas (*Background* o *Application*). La combinación de pre-filtros léxicos, consultas programáticas asíncronas sobre Semantic Scholar en 12 áreas disciplinarias y esquemas de clasificación estructurados con Gemini permitió cerrar el déficit en clases minoritarias (*Modification_Improvement*, *Further_Reading*, *Gap*, entre otras) alcanzando 2.295 instancias reales por categoría sin recurrir a datos sintéticos.
* **Rescate semántico continuo frente a decisiones discretas:** El uso de probabilidades continuas ($0.0$ a $1.0$) vía Pydantic posibilitó implementar mecanismos de rescate secundario, recuperando contextos ricos donde la categoría secundaria reflejaba el verdadero matiz retórico de la cita.
* **Rigor evaluativo con política estricta de aislamiento (*No-Leakage*):** La partición por grupos sobre pares documentales (`pair_id`) garantiza que la evaluación del 15% (3.105 instancias destinadas a pruebas a ciegas con anotadores humanos) mida la capacidad real de generalización lingüística ante artículos y autores completamente inéditos, eliminando el sesgo por co-ocurrencia léxica compartida.
* **Enriquecimiento denso para modelado avanzado:** La integración de fragmentos estructurados (*Top-3 Chunks*) mediante representaciones vectoriales reales de SciBERT transforma este corpus de una simple tarea de texto plano a un recurso enriquecido, sentando las bases para alimentar modelos densos basados en contexto o pipelines de recuperación aumentada (RAG).